### ISSUE TITLE
Strategy for pulling in upstream changes?

### ISSUE THREAD

**Issue by itsdalmo** [awslabs/aws-deployment-framework#11]
According to the [documentation](https://github.com/awslabs/aws-deployment-framework/blob/master/docs/admin-guide.md#src-folder) the `src/bootstrap_repository` and `src/pipelines_repository` folders should be pushed to CodeCommit as standalone repositories, however I'm wondering if you have any recommended `git` strategy for pulling in changes from upstream (this repository)?

Ideally the strategy should make it easy to know which revision of the upstream (this repo) that the standalone versions of `bootstrap_repository` and `pipelines_repository` are based off, and be transparent about whether they have diverged from the upstream. Achieving this with the current requirement to split folders into separate git repositories seems to require pretty advanced git usage (e.g. `subtree` or `filter-branch`), and as a result it feels more error-prone and less user friendly.

I think the easiest solution would be that `bootstrap_repository` and `pipelines_repository` were just mirrors of the complete repository, and the Python code/CodePipeline was adapted to run code from the respective subdirectories. This would allow a much more straight forward git strategy:

- Fork `aws-deployment-framework`, clone the fork and set upstream.
- Add remotes for the CodeCommit repositories for `bootstrap_repository` and `pipelines_repository`.
- Changing e.g. `deployment_map.yml` happens in the fork, and is pushed out to CodeCommit.
- New changes in upstream can be pulled in via `merge` or `rebase`, and then pushed out to CodeCommit.

Would this work, or do you have a solution that works with the current structure?

**Comment by bundyfx** [comment]
Howdy, 

Indeed there are more optimal ways to work with this repository as an upstream while keeping private repositories in sync when working with ADF. One way of tackling this could be shifting all of the codebase into its own folder and keeping configurations (adfconfig, deployment_map) in their own separate structure. That way any changes to the underlying codebase could be pulled down from upstream and not conflict with any configuration settings that have been made within the users own environment. I'll tag this as an enhancement for now and think more about optimizing the structure for the next release.

Cheers!

**Comment by itsdalmo** [comment]
Hi and thanks for the quick response!

>That way any changes to the underlying codebase could be pulled down from upstream and not conflict with any configuration settings that have been made within the users own environment. 

That is true for e.g. a fork of the entire repository, but things get a bit complicated when you want to propagate said upstream changes to the CodeCommit repositories (`bootstrap_repository` and `pipelines_repository`). How do you solve this today?

**Comment by bundyfx** [comment]
Sorry the delay, we have been in discussion about how to best make this as user friendly as possible while maintaining DRY principals within the codebase. It's still a work in progress at the moment. In regards to your suggestion: 

> bootstrap_repository and pipelines_repository were just mirrors of the complete repository.

Just so I understand correctly, are you suggesting make the bootstrap and pipelines repository folders contain the whole repository? _(in each of them?)_  - How would this work with the duplicate folders/files that would be created, and updating these into the future?

Happy to get more feedback, and of course happy for PR's on this also with suggestion.

**Comment by itsdalmo** [comment]
> Just so I understand correctly, are you suggesting make the bootstrap and pipelines repository folders contain the whole repository? (in each of them?)

I'm not suggesting that the _folders_ contain the whole repository, but that what is pushed to CodeCommit is the whole repository (as in `aws-deployment-framework`) instead of just the individual subfolders. I'll see if I can't put together a PR :)

**Comment by itsdalmo** [comment]
We ended up creating a private copy of `aws-depoloyment-framework`, setting the original as the upstream, and then using `git subtree` to push the folders in `src/` to their respective CodeCommit repositories.

To pull in upstream changes:
```bash
git remote add upstream git@github.com:awslabs/aws-deployment-framework.git
git pull upstream <tag>
```

To push e.g. `src/pipelines_repository` to CodeCommit:
```bash
git subtree push --prefix=src/pipelines_repository https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/aws-deployment-framework-pipelines master
```

Works pretty well, so I'll close this issue and leave the comment as a reference for anyone else who might wonder the same 😅
