### ISSUE TITLE
Github Repository which differs from Pipeline Name causes Codebuild failure

### ISSUE THREAD

**Issue by javydekoning** [awslabs/aws-deployment-framework#116]
```
pipelines:
  - name: sample-cdk-fargate-app
    type: github-cloudformation
    action: replace_on_failure
    params:
      - ProjectName: "aws-cdk-playground" #Name of the Github Repository
      - Owner: "mygithubuser" #Github user
      - OAuthToken: "/tokens/oauth/github" #/path/to/ssm/param
      - WebhookSecret: "/tokens/webhooksecret/github"
      - Image: "aws/codebuild/standard:2.0"
    targets:
      - /ouname
```

Results in this issue: 

```
[Container] 2019/08/01 15:05:14 Running command python adf-build/generate_params.py 
Traceback (most recent call last): 
  File "/codebuild/output/src214747102/src/adf-build/python/parameter_store.py", line 71, in fetch_parameter 
    WithDecryption=with_decryption 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation:  
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "adf-build/generate_params.py", line 170, in <module> 
    main() 
  File "adf-build/generate_params.py", line 163, in main 
    boto3 
  File "adf-build/generate_params.py", line 35, in __init__ 
    [self.account_ous, self.regions] = self._fetch_initial_parameter() 
  File "adf-build/generate_params.py", line 41, in _fetch_initial_parameter 
    "/deployment/{0}/account_ous".format(self.build_name) 
  File "/codebuild/output/src214747102/src/adf-build/python/parameter_store.py", line 76, in fetch_parameter 
    'Parameter {0} Not Found'.format(name) 
errors.ParameterNotFoundError: Parameter /deployment/aws-cdk-playground/account_ous Not Found 
```

The SSM param is actually called: `/deployment/sample-cdk-fargate-app/account_ous`, hence it looks like the pipeline name cannot be different for the `ProjectName`. 

Perhaps there should be a separate param for Repo as it currently references the `ProjectName` param here: 

https://github.com/awslabs/aws-deployment-framework/blob/2043c524a48d45dd711b62f60f4dbde7384b6e10/src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/github-cloudformation.yml.j2#L271

**Comment by bundyfx** [comment]
Hi Javy, thanks for raising this. We should add a repository name parameter like we do for the CodeCommit version of that pipeline type. That way, you can just pass the Repository name in as a parameter rather than it being assumed by the pipeline name. If you would like to add this in, take a look at how we implement this same logic [here](https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-cloudformation.yml.j2#L4).
