### ISSUE TITLE
Support overriding stack name

### ISSUE THREAD

**Issue by ikben** [awslabs/aws-deployment-framework#122]
I added these changes to the cc-cloudformation.yml.j2 in my own reepo, to add support to specifying the CloudFormation StackName: https://github.com/awslabs/aws-deployment-framework/commit/664d6af

If there are no objections I'd like to:

- Add the same parameter to every jinja file
- Document this in the user guide

I'm opening this issue to figure out if this is the preferred approach / would be accepted before doing the bulk of the effort.

**Comment by ikben** [comment]
Another approach might be to check if `StackPrefix` is empty, and if it is to remove the leading `-`, but that will generate a more complicated !If.

Moving the `-` to the StackPrefix might be possible too, but that would be a breaking change (for people using their own prefix)

**Comment by ikben** [comment]
I have been thinking about this more, and you night also want this to be a parameter in the targets section. Because that would allow for custom naming where needed, and deploying the same stack multiple times in the same account.

Eg:
```
targets:
  - name: 111111111111
    stack_name: my-stack-test
  - name: 11111111111
    stack_name: my-stack-prod
```

**Comment by bundyfx** [comment]
Nice one, I also think this is the right way to go, stack name should be configurable in the targets section, Also I agree that we need to move the **-** to the stack prefix itself.
