### ISSUE TITLE
Problem with package transform and multiple regions

### ISSUE THREAD

**Issue by amimarkels** [awslabs/aws-deployment-framework#134]
when working with nested stacks and multiple regions, the package_transform.sh is successfully fetching the bucket name for the other region but because there is no "--region" flag in the `sam package` command it will try to access the bucket in the wrong region (the main region).

we solved it by modifying line 26 with --region flag:
sam package --s3-bucket $bucket --output-template-file $CODEBUILD_SRC_DIR/template_$region.yml **--region $region**

**Comment by bundyfx** [comment]
Hi @amimarkels 

Thanks for the suggested fix. Would you please be able to make a PR for this into the helper file as you mentioned, this is the way the helper is intended to work.

**Comment by amimarkels** [comment]
already submitted.
