### ISSUE TITLE
Protect ADF baseline resources using SCPs

### ISSUE THREAD

**Issue by shendriksen** [awslabs/aws-deployment-framework#146]
I have recently been asked whether we can lock down the baseline resources using SCPs.
It appears that we should be able to do this now using the below example:

https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_example-scps.html#example-scp-restricts-with-exception

**Comment by bundyfx** [comment]
That is correct, you can use SCPs to control this behavior. :rocket:
