### ISSUE TITLE
Cleanup of resources after moving account from OU to root or other OU

### ISSUE THREAD

**Issue by elmoenco** [awslabs/aws-deployment-framework#148]
I'm using ADF primarily to provision accounts with capabilities (networking, IAM) and guardrails (compliance). I'd like to have some form of LCM on sandbox accounts: when they're not being used they will be moved to an 'Inactive' or 'ToBeDeleted' OU.  
At the moment the coupling between the pipeline and the deployed stack breaks when moving an account to root / another OU, as mentioned in the documentation ('The resources that were created as outputs from this pipeline will not be removed by this process.') which can be a security risk.
I'd like ADF to optionally be able to delete the deployed stacks when moving an account. 

Before I misuse ADF configuration options or create a cleanup mechanism outside of ADF, I'd like to know if cleanup is something ADF should do in the first place.

**Comment by bundyfx** [comment]
cc @thomasmcgannon for more input.
I think the bootstrapping aspect could be extended to do more, however where ADF really shines is the pipelines component, ideally less should be in the bootstrapping "base" stacks of accounts and more should come through structured pipelines.
