### ISSUE TITLE
Allow OU targets in deployment_map.yml that do not (yet) contain accounts

### ISSUE THREAD

**Issue by thiezn** [awslabs/aws-deployment-framework#15]
Hi,

Would it be possible to add an OU that does not (yet) contain any accounts to be provided to the deployment_map.yml in the pipelines repository? This could be helpful when introducing new OUs to the AWS organisation. 

I noticed that the pipeline aws-deployment-framework-pipelines running in the deployment account gives the below error during the build phase:

```
========================== 22 passed in 0.31 seconds ===========================
 [Container] 2019/03/14 16:13:33 Running command python ./adf-build/generate_pipelines.py
Traceback (most recent call last):
 File "./adf-build/generate_pipelines.py", line 147, in <module>
 main()
 File "./adf-build/generate_pipelines.py", line 143, in main
 cloudformation.create_stack()
 File "/codebuild/output/src007560056/src/adf-build/shared/python/cloudformation.py", line 254, in create_stack
 create_change_set = self._create_change_set()
 File "/codebuild/output/src007560056/src/adf-build/shared/python/cloudformation.py", line 191, in _create_change_set
 ChangeSetType=self._get_change_set_type())
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
 return self._make_api_call(operation_name, kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
 raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: [/Resources/Pipeline/Type/Stages/3/Actions] 'null' values are not allowed in templates
 [Container] 2019/03/14 16:13:37 Command did not exit successfully python ./adf-build/generate_pipelines.py exit status 1
[Container] 2019/03/14 16:13:37 Phase complete: BUILD Success: false
[Container] 2019/03/14 16:13:37 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: python ./adf-build/generate_pipelines.py. Reason: exit status 1

```

My deployment_map.yml file is similar to the below, where the /development OU does have an account, but the /production OU doesn't:

```
pipelines:
  - name: sample-vpc # The name of your pipeline (This will match the name of your repository)
    type: cc-cloudformation # The pipeline_type you wish to use for this pipeline
    params:
      - SourceAccountId: 111111111111
      - NotificationEndpoint: clouddelivery@rabobank.com # The Notification (user/team/slack) responsible for this pipeline
    targets: # Deployment stages
      - path: /development
        regions: eu-west-1
      - path: /production
        regions: eu-west-1
```

I've briefly reviewed the stacktrace and I suspect my deployment_map.yml will trigger the [following code](https://github.com/awslabs/aws-deployment-framework/blob/d90078b5ca16312f9d04ad1bad690a2c0f40c9ed/src/pipelines_repository/adf-build/target.py#L91-L100) and fill the self.target_structure.account_list with accounts if there are any. 

Perhaps we can check if the list is emtpy [somewhere here](https://github.com/awslabs/aws-deployment-framework/blob/d90078b5ca16312f9d04ad1bad690a2c0f40c9ed/src/pipelines_repository/adf-build/generate_pipelines.py#L118) to avoid creating a cloudformation stack if there is none? 

I have to say I'm very new to adf so might be completely off here in my assumptions, and doing something else wrong that causes this issue.

Kind  regards,
Thiezn

**Comment by bundyfx** [comment]
Hi @thiezn 

Adding an OU to a pipeline that doesn't include any accounts is an interesting one. My main concern with adding this functionality is that the deployment map *could* potentially no longer be accurately representing the structure of the pipeline. Take for example for following pipeline definition *(if this was in our deployment_map)*:

>       - /sandbox
>       - /testing
>       - /production

If we had accounts only in *sandbox* and *production* then the pipeline steps would be Source -> Build -> Sandbox -> Production. However that would not be reflected in the deployment map and could raise confusion.

I think we could do better with the error messaging around this though. Happy to discuss potential other ways of making this work *(Maybe some parameter that gets passed in?)* as I do understand that pipelines might want to be defined ahead of time prior to accounts existing.

**Comment by thiezn** [comment]
Hi @bundyfx 

Have to agree it can become confusing, especially if the target structure becomes larger. Its easy enough to work around this so probably a more descriptive error message would be sufficient.

Perhaps this can be done easily by raising an exception in generate_pipelines.py when target_structure.account_list is empty?

**Comment by bundyfx** [comment]
Sounds good, I'll dig into this shortly and get it sorted.
