### ISSUE TITLE
Webhook could not be registered with GitHub

### ISSUE THREAD

**Issue by kahilof** [awslabs/aws-deployment-framework#179]
Hello,

After upgrading to v2.1.1, I tried to create a new pipeline in deployment_map with GitHub as a source. However the stack for this one fails with "Webhook could not be registered with GitHub. Error cause: Not found [StatusCode: 404, Body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}] (Service: AWSCodePipeline; Status Code: 400" 

Steps to generate the issue:
1. Upgraded successfully from v1.6 to 2.1.1
2. Old pipelines deployed successfully (all using Github as a source)
3. Tried to add a new pipeline to the map to deploy a simple template (new sns topic, cloudwatch rule and a policy)
4. The stack fails with above error

**Comment by bundyfx** [comment]
Hi @kahilof 

Did you see the release notes for 2.0.0? We updated the way ADF works with secret type values and moved all of these from parameter store into Secrets Manager. Have you updated your pipelines to match this new structure and populated Secrets Manager with your oauth token (see the example -> https://github.com/awslabs/aws-deployment-framework/releases/tag/v2.0.0)

**Comment by kahilof** [comment]
Thanks flynn for your support, below is how we have solved the issue:

1. Removed new pipeline definition from deployment_map
2. Re-run main deployment map to make sure it will finish successfully
3. Added new definition again with same github token
4. Re-run main deployment again, new template deployed successfully

**Comment by kahilof** [comment]
I'm closing this as the issue, has been solved
