### ISSUE TITLE
Rename bootstrap_repository/global.yml to example-global.yml

### ISSUE THREAD

**Issue by thiezn** [awslabs/aws-deployment-framework#18]
Hi @bundyfx 

Would it be an idea to rename the bootstrap_repository/global.yml to bootstrap_repository/example-global.yml ? This would give the proper signal to users of ADF that they are supposed to tweak global.yml to their own requirements, similar to what you do with the adfconfig.yml file. 

This would also make it easier for us to upgrade our adf environment to later versions.

Cheers,
Thiezn

**Comment by bundyfx** [comment]
Hi @thiezn 

There is indeed an aspect of global.yml that should be configured by the users of ADF. This is mostly related to the `cloudformation-deployment-role-policy` that is created as part of the template. This policy allows what CloudFormation can and cannot do within the accounts it is deployed into. While this policy can and should be configured to align with the specific OU it's working with, the other content within the file should not be altered and is required for the pipelines aspect of ADF to function.

We are still working out a solid way to handle working with the upstream content easier and avoiding merge conflicts when working with updates. as mentioned in #11. For now I will close this one as we will look further into the proper structure to use moving forward with examples and files in general.

Cheers!
