### ISSUE TITLE
Unclear documentation for Slack integration setup for Secrets Manager

### ISSUE THREAD

**Issue by eriklz** [awslabs/aws-deployment-framework#181]
In docs/admin-guide.md, in section "Integrating Slack" it is stated:

"Once created, copy the webhook URL and create a new secret in Secrets Manager on the Deployment Account with the type of 'Other' (eg API Key). Give the Secret a name that maps to the channel that the webhook is authorized to send messages to. For example, if I had created a webhook for my team called team-bugs this would be stored in Secrets Manager as /adf/slack/team-bugs."

However, the documentation does not state that the encryption key to use is the "aws/secretsmanager" one (there is at least also the codepipeline key) and it does not state that the format of the secret data should be

{
   "channelname": "webhookurl"
}

which requires to look at the source for the lambda function to see what it should be.

**Comment by bundyfx** [comment]
Thanks @eriklz - I agree this documentation is a tad confusing. If you would like to open a PR to fix this please do, that would be much appreciated.  Otherwise I will fix this in the next release 😄 

Thanks!

**Comment by eriklz** [comment]
Submitted a pull request @bundyfx .

**Comment by bundyfx** [comment]
Thanks!
