### ISSUE TITLE
Codebuild Cypress Testing Automation Error

### ISSUE THREAD

**Issue by jallohi** [awslabs/aws-deployment-framework#184]
tput: No value for $TERM and no -T specified 
================================================================================ 
 
  (Run Finished) 
 
 
       Spec                                              Tests  Passing  Failing  Pending  Skipped   
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐ 
  │ ✔  examples/actions.spec.js                 00:14       13       13        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/aliasing.spec.js                00:01        2        2        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/assertions.spec.js              00:02        8        8        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/connectors.spec.js              00:01        5        5        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/cookies.spec.js                 00:02        5        5        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/cypress_api.spec.js             00:02       13       13        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✖  examples/demo.spec.js                    00:11        1        -        1        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/files.spec.js                   00:02        4        4        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/local_storage.spec.js           00:01        1        1        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/location.spec.js                00:01        3        3        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/misc.spec.js                    00:03        6        6        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/navigation.spec.js              00:02        3        3        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/network_requests.spec.js        00:03        7        7        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/querying.spec.js                00:01        4        4        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/spies_stubs_clocks.spec.js      00:04        5        5        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/traversal.spec.js               00:04       18       18        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/utilities.spec.js               00:03        6        6        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/viewport.spec.js                00:03        1        1        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/waiting.spec.js                 00:05        2        2        -        -        - │ 
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤ 
  │ ✔  examples/window.spec.js                  00:01        3        3        -        -        - │ 
  └────────────────────────────────────────────────────────────────────────────────────────────────┘ 
    ✖  1 of 20 failed (5%)                      01:16      110      109        1        -        -   
 
·[?25hnpm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! wq-sampling@1.0.0 cyRun: `cypress run` 
npm ERR! Exit status 1 
npm ERR!  
npm ERR! Failed at the wq-sampling@1.0.0 cyRun script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!     /root/.npm/_logs/2019-11-14T23_08_35_930Z-debug.log 
npm ERR! Test failed.  See above for more details. 
 
[Container] 2019/11/14 23:08:35 Command did not exit successfully npm test exit status 1 
[Container] 2019/11/14 23:08:35 Phase complete: POST_BUILD State: FAILED 
[Container] 2019/11/14 23:08:35 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm test. Reason: exit status 1

**Comment by bundyfx** [comment]
Hi @jallohi 

This looks like a general CodeBuild failure when running Cypress. There is not really enough information here for us to know if this has to do with ADF or if its just something missing in your config/buildspec for cypress to run successfully.
