### ISSUE TITLE
Build stage configuration flag "enabled" for provider codebuild not working properly

### ISSUE THREAD

**Issue by eriklz** [awslabs/aws-deployment-framework#189]
I have tried to use the enabled flag to disable the build stage in some pipelines, without success and different errors.
Looking at the code there seeem to be a discrepancy in validation and and runtime checks for this flag:

In src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py:

```
DEFAULT_CODEBUILD_BUILD = {
    Optional("provider"): 'codebuild',
    Optional("enabled"): bool,
    Optional("properties"): CODEBUILD_PROPS
}

```

Enabled flag is defined at the same level as provider and properties.
However, in src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk-stacks/main.py:

```
        if 'codebuild' in _build_name and stack_input["input"]["default_providers"]["build"].get("properties", {}).get('enabled', True):
            _stages.append(
                adf_codebuild.CodeBuild(
```

This code assumes that enabled is located under properties rather than at the same level.
It does not work really to leave out the build stage entirely even though it is optional according to the schema validation, since further up in the same file there is:

`_build_name = stack_input['input']["default_providers"]["build"]["provider"].lower()
`

i.e. the code assumes that there always is a build entry with a provider entry underneath it.

**Comment by bundyfx** [comment]
Thanks @eriklz 

Good catch it should not be under the properties level but should rather be checking a level-up as the schema shows, I will fix this one and bundle it into the next release.
