### ISSUE TITLE
Allow adf to deploy in the master account

### ISSUE THREAD

**Issue by thiezn** [awslabs/aws-deployment-framework#19]
Hi,

Forgive me for asking for all these new shiny features, I DO like the ADFramework :)

Would it be possible to raise an enhancement request for allowing us to deploy resources through adf in the master account? This would make life easier for us for example to:
- Enable organisational wide cloudtrail
- Enable organisational wide config
- Enable guardduty
- etc..

Cheers,
Mathijs

**Comment by bundyfx** [comment]
Hi @thiezn 

Understandably there are some resources you might want to configure in the Master account. What are your thoughts on potentially tweaking the _adfconfig.yml_ to allow the automatic configuration of organizational wide services? This could just be a boolean in the config file, something like:

```
config:
  main-notification-endpoint: 
    - type: email # slack or email
      target: jon.doe@email.com  
  moves:
    - name: to-root
      action: safe
  organizational-services:
    - name: config
      enabled: true
    - name: cloudtrail
      enabled: true
` ``

Would something like this suffice for your needs?

**Comment by thiezn** [comment]
Hi @bundyfx 

That would be a nice feature but I do worry that would make less flexible for customers and a burden on your time. You would have to do this for each service that customers might want to enable on the master account. 

In your example you mention config and cloudtrail, but we for instance would also want to enable guard duty, create SES/SNS alerts, roll out IAM roles, automate account creation/ou assignments etc.

It would be better if we could have a dedidated CodeCommit and CodePipeline and roll them out to master, just like we do for non-master accounts. I do understand this is a bit of a chicken-egg problem, not sure how to get around that.

Cheers,
Mathijs

**Comment by oaksenov** [comment]
I second the request, it would be nice to run pipelines against master account too.
