### ISSUE TITLE
Enhancement: initial setup - add custom resource to check for right region

### ISSUE THREAD

**Issue by mdaehnert** [awslabs/aws-deployment-framework#191]
ADF needs to be initially setup on us-east-1 for CloudWatch event to work on MoveAccount.
It might happen, that a customer installs ADF in its home region.
We therefore should add a CustomResource-Lambda which checks the current region and fails with a meaningful message. Otherwise customers might struggle some time to figure out the issue of missing event triggering.

**Comment by bundyfx** [comment]
Good one, I think something as simple as checking the AWS_REGION environment variable in one of the existing initial custom resources and failing there if its not us-east-1 will be completely valid for this. Will go into next release.
