### ISSUE TITLE
Initial setup of v2.1.2 without setting "MainNotificationEndpoint" throws an error

### ISSUE THREAD

**Issue by mdaehnert** [awslabs/aws-deployment-framework#192]
When creating initial ADF setup and not setting "MainNotificationEndpoint", then the initial Step Function on master account throws an error.

**Suggested mitigations:**
* Enhance documentation, that MNE _is_ required when setting up ADF for the first time.
* Do a pre-check of parameters in initial Step Functions lambda call to provide a meaningful error message.

**Steps for reproducting:**
a.) Setup ADF without mentioning _MainNotificationEndpoint_ and check Step Functions

b.) Execute _DetermineEventFunction_ lambda with following input:
```js
{
  "version": "0",
  "id": "...",
  "detail-type": "AWS API Call via CloudTrail",
  "source": "aws.organizations",
  "account": "...",
  "time": "2019-11-20T14:45:45Z",
  "region": "us-east-1",
  "resources": [],
  "detail": {
    "eventVersion": "1.05",
    "userIdentity": {
      "type": "IAMUser",
      "principalId": "...",
      "arn": "...",
      "accountId": "...",
      "accessKeyId": "...",
      "userName": "...",
      "sessionContext": {
        "sessionIssuer": {},
        "webIdFederationData": {},
        "attributes": {
          "mfaAuthenticated": "false",
          "creationDate": "2019-11-20T06:12:45Z"
        }
      },
      "invokedBy": "signin.amazonaws.com"
    },
    "eventTime": "2019-11-20T14:45:45Z",
    "eventSource": "organizations.amazonaws.com",
    "eventName": "MoveAccount",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "...",
    "userAgent": "signin.amazonaws.com",
    "requestParameters": {
      "accountId": "...",
      "destinationParentId": "...",
      "sourceParentId": "..."
    },
    "responseElements": null,
    "requestID": "...",
    "eventID": "...",
    "eventType": "AwsApiCall"
  }
}
```

**Update:**
Cleaning up and re-creating from scratch with _MainNotificationEndpoint_ (only change) succeeds. So the error has to be from this parameter.

**Comment by bundyfx** [comment]
Thanks @mdaehnert - Good catch, changes to the docs to ensure the Main Notification Endpoint is defined will go into the next release of ADF. We will also handle the errors better to ensure a valid error message is shown in these specific cases.

**Comment by bundyfx** [comment]
The SAR now lists this as non-optional. It is something we could potentially make optional in the future however.
