### ISSUE TITLE
Pipeline on non-deployment accounts

### ISSUE THREAD

**Issue by Baalakay** [awslabs/aws-deployment-framework#199]
Any way to configure the pipeline to be created in same account as the repo listed in the deployment_map.yaml, instead of the main deployment acount?

**Comment by bundyfx** [comment]
Hi @Baalakay 

Not out of the box no, however you could deploy a stack via a pipeline in the deployment account into the accounts where the code is kept that contains a Codepipeline and associated resources. The idea behind a centralized deployment account is to promote transparency and reduce duplicate pipelines/deployments of workloads.
