### ISSUE TITLE
Enhance ramp up for newcomers - Add workflow/architecture diagram on documentation

### ISSUE THREAD

**Issue by mdaehnert** [awslabs/aws-deployment-framework#211]
It would be great if newcomers could see some architectural / workflow diagram on "How ADF works". e.g.: What happens, once a new account is created and moved into an OU.

I'll create a fork with diagram(s). Let's discuss together before merged.

**Comment by bundyfx** [comment]
This would be very much appreciated! Thanks @mdaehnert
