### ISSUE TITLE
A quick hack to generate an accounts.yml file for your existing accounts (for ADF 3.x)

### ISSUE THREAD

**Issue by ErikMeinders** [awslabs/aws-deployment-framework#214]
This is actually not an issue, but related to the issue #213 

For completeness sake, I wanted documentation of all existing accounts in the proper config file format.
I ran this in Cloud9 using python2.7

You can find it here https://github.com/ErikMeinders/adf3-createaccountlist.git

**Comment by bundyfx** [comment]
Thanks @eriklz 

Closing this one now, if you would like to add something to the documentation about this with a link to a gist please feel free 🎉
