### ISSUE TITLE
Add the ability to specify which region to extract an ssm param for in the parameter files

### ISSUE THREAD

**Issue by thomasmcgannon** [awslabs/aws-deployment-framework#22]
Currently you can use the `resolve:` keyword in the params .json files to resolve parameters that are stored in the SSM Parameter Store, however this only allows you to retrieve the parameter form the main deployment account region.

```json
{
    "Parameters" : {
        "SomeParam":"resolve:/path/to/key"
    }
}
```

Having a way to specify or override the region (like below for example), would help with multi-region deployments.

```json
{
    "Parameters" : {
        "SomeParam":"resolve:/**region**/path/to/key"
    }
}
```

**Comment by bundyfx** [comment]
PR #26 has been merged into master

If you wish to resolve parameters in the default deployment region you can use resolve:/path/to/param or if you wish to resolve from a different region within the deployment account you can pass resolve:eu-west-1:/path/to/param (eu-west-1 being the example)

**Comment by tmaior** [comment]
hello, can help?
not working in:
AWS::ECS::TaskDefinition


Environment:
            - Name: SLACK_WEBHOOK
              Value: !Sub "{{resolve:us-east-1:/GENERAL/SECURITY_SLACK_WEBHOOK:1}}"
