### ISSUE TITLE
Request for example file

### ISSUE THREAD

**Issue by ErikMeinders** [awslabs/aws-deployment-framework#220]
The file

/aws-deployment-framework-bootstrap/adf-bootstrap/deployment/global-iam.yml

doesn't come with an example version. When merging a PR, this file always needs attention as there is no example-global-iam.yml in this directory (as opposed to its parent directory) so it's always reset to the distributed version of the file. Would be nice to not have the actual file distributed, or with better defaults ...

**Comment by sbkok** [comment]
Hi Erik,

I don't think I completely understand your request.
If you do not create a more specific `global-iam.yml` in the OU directory, like the `deployment` one you put in the example (`adf-bootstrap/deployment/global-iam.yml`), it would default to the `adf-bootstrap/global-iam.yml` definition.

As documented in the upgrade guide, you will need to create that file once from the `example-global-iam.yml`, such that any future updates of ADF will not overwrite your IAM policies.

What issue are you running into exactly?

**Comment by sbkok** [comment]
Hi @ErikMeinders, after looking into the file structure more closely I came to understand what you ran into. Thanks for raising awareness on this issue. I've filed a PR to get this changed.
