### ISSUE TITLE
adf-automation-role missing permissions for enabling termination protection on adf-codecommit-* repos

### ISSUE THREAD

**Issue by StewartW** [awslabs/aws-deployment-framework#221]
` Error: An error occurred (AccessDenied) when calling the UpdateTerminationProtection operation: User: arn:aws:sts::XXXXX:assumed-role/adf-automation-role/create_repo_XXXX is not authorized to perform: cloudformation:UpdateTerminationProtection on resource: arn:aws:cloudformation:eu-west-2:XXXX:stack/adf-codecommit-/43a78870-3ebf-11ea-9fec-06452e71541c | (cloudformation.py:233)`

**Comment by bundyfx** [comment]
3.0.4 - Pending merge. release is on SAR, closing.
