### ISSUE TITLE
CodeBuild failure: Newer version of CDK is required

### ISSUE THREAD

**Issue by sbkok** [awslabs/aws-deployment-framework#223]
While running ADF v2.1.2, the `aws-deployment-framework-pipelines` pipeline fails in the CodeBuild step. Similar to  #182.

It fails with a message stating:
```
A newer version of the CDK CLI (>= 1.21.0) is necessary to interact with this app
```

When it tries to execute:
```
Command did not exit successfully cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null exit status 1
```

---

**Root cause:**
I have found the root cause of the problem. In the list of required python modules required by: `adf-build/shared/requirements.txt`, it is missing two requirements:
```
aws_cdk.cx_api==1.16.3
aws-cdk-region-info==1.16.3
```

---

**Workaround:**
For those who are unable to upgrade to the latest release of ADF yet, apply the following patch file on your `aws-deployment-framework-bootstrap` repo:
```patch
--- adf-build/shared/requirements.txt
+++ adf-build/shared/requirements_patched.txt
@@ -49,4 +49,6 @@ aws_cdk.aws_cloudwatch==1.16.3
 aws_cdk.aws_kinesis==1.16.3
 aws_cdk.aws_s3_assets==1.16.3
 aws_cdk.aws_sns_subscriptions==1.16.3
+aws_cdk.cx_api==1.16.3
+aws-cdk-region-info==1.16.3
 aws-cdk.core==1.16.3
```

Save this patch file as `version_lock.patch` in the root of the repo.
Then execute:
```bash
patch adf-build/shared/requirements.txt < version_lock.patch && rm version_lock.patch
git add adf-build/shared/requirements.txt
git commit -m "Version lock missing CDK dependencies"
```

---

**How about the latest ADF version 3.0.3?**

This issue is not affecting anyone yet, as ADF includes a recent release of CDK in its requirements. However, it has the same problem where some dependencies of CDK are not version locked in the `requirements.txt`. So in case an organization would run ADF v3.0.3 and CDK gets updates that break the version compatibility, it will affect them too.

I will push a PR to get this fixed in the next release.

**Comment by slipdexic** [comment]
This has been a major issue for us spent nearly a day trying to work out why pipeline deployment was broken when we added a new production stage.
Is there a way to be fixed to a CDK version. 
So as the CDK rapidly changes ( and also sometimes adds breaking changes) we are not effected unless we upgrade to latest version via SAR

**Comment by sbkok** [comment]
I’m sorry for this experience. ADF had version locks in place for all the direct dependencies. However, some of them referred to other CDK modules with ^ (ie newest possible version). This indirect dependency is the problem that you ran into. With version 1.20 of CDK that introduced an issue with its compatibility.

A fix has been merged with #225. We locked the version of all CDK dependencies that are in use by ADF indirectly as well.

However, that fixes the problem for 3.0.4, not 2.x ADF installations. Plus, if CDK decides to include another dependency with a next version we might run into this again.

It might be worth it to write an assertion that would block the release if an indirect dependency isn’t version locked correctly. I will discuss this with the team.

**Comment by slipdexic** [comment]
Simon,
Thank you for your explanation. That makes sense.
Sorry off-topic for this thread going forward is there a forum /Gitter channel like the CDK has for this project? As I would be interested in getting involved.
Also, where can I find guidance on upgrading to 3.0.4
Thanks 
Darryl

**Comment by sbkok** [comment]
No problem at all, I'm certain it will be useful for others too. To upgrade you can [follow this guide](https://github.com/awslabs/aws-deployment-framework/blob/master/docs/admin-guide.md#updating-between-versions).
In terms of Gitter or other channels, we don't have one yet. I've asked the team if there are any plans to set it up. Will keep you updated.
Cheers!
