### ISSUE TITLE
Insecure bucket/key policy?

### ISSUE THREAD

**Issue by itsdalmo** [awslabs/aws-deployment-framework#23]
Just noticed some `aws:PrincipalOrgID` use which I think might be unintended:
- [S3 bucket policy](https://github.com/awslabs/aws-deployment-framework/blob/master/src/bootstrap_repository/deployment/global.yml#L613)
- [KMS key policy](https://github.com/awslabs/aws-deployment-framework/blob/master/src/bootstrap_repository/deployment/global.yml#L104)

The way I understand this condition when used on a bucket/key policy, it actually gives any account in the organisation said privileges. Which means that all accounts in the org is given `s3:Put*` (which includes `s3:PutBucketPolicy` and friends) on the bucket and `kms:Decrypt` on the key. 

If I've understood this correctly it should probably be fixed?

**Comment by bundyfx** [comment]
Hi @itsdalmo 

When it comes to the S3 Bucket Policy I agree. We don't want any accounts being able to set the Bucket Policy on the Deployment Account. This is fixed now in this PR. 

When it comes to the KMS Key, this is essentially the same way as we had it before, however now we are able to scale ADF past the confines of the KMS Key Policy (32kb). Previously, we were appending each new account that was bootstrapped to have access to use the key. It does mean that any role within the organization _(that has a policy to allow it)_ can potentially call kms:decrypt on something within the Pipeline Bucket however this bucket should not contain any private information _(only deployment artifacts)_ . This key should only ever be used for the automation and cross account/region replication aspects that CodePipeline requires. Happy to get your thoughts on this further however.

**Comment by bundyfx** [comment]
For now i'll close this one off however am happy to open it again and discussion further KMS/S3 related security policies.
