### ISSUE TITLE
ADF fails to update account alias with new account

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#242]
I created a new account by defining the account in yaml in bootstrapping repo. Account got created, but even few consecutive re-runs the new account still does not have an alias. I cannot see one in IAM console and this is the CLI response:
`end@TMP-5CG7384720:~$ aws iam list-account-aliases
{
    "AccountAliases": []
}`
Bootstrapping pipeline build logs state that 
`2020-02-14 14:06:24,959 | INFO | __main__ | Ensuring account alias for 711028751955 of dataanalytics | (main.py:82)`

There were also some other issues bootstrapping new account, but maybe I will create another issue after I have some kind of a picture what actually happened.

**Comment by bundyfx** [comment]
Interesting, we will take a look into this to ensure its working as intended. Thanks for reporting it @hynynen 🎉

**Comment by hynynen** [comment]
Now that I added the account alias manually, I found the likely reason: account alias already exists. So in this case it would be nice to have more informative response from ADF.
