### ISSUE TITLE
Error upgrading to v3.0.4

### ISSUE THREAD

**Issue by adamcoxon** [awslabs/aws-deployment-framework#245]
### Summary
When attempting to upgrade from 2.1.2 -> 3.0.4 we are getting an error with the CF Stack. The stack is now stuck in Update Rollback Failed state as there are a few resources that failed to update and rollback.

### Steps to reproduce
* Follow the instructions to upgrade the stack via Serverless Application Repository. 
* Wait for the stack to fail to update
* Wait for the stack to fail rollback

### Errors
All the AWS:Serverless:Lambda resources failed to upgrade and give the following error:

_Your access has been denied by S3, please make sure your request credentials have permission to GetObject for awsserverlessrepo-changesets-plntc6bfnfj/AIDAVRA52KSB5Q7HJA24L-ddc43135-6f89-466c-8d75-23aabe5d0dd6. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 9bbb3491-8c02-4799-b823-4cb2f953f65f)_

Looking into the CF Template it is trying to deploy it seems that the permissions on the _'awsserverlessrepo-changesets-plntc6bfnfj'_ S3 Bucket is not allowing our role to get the Lambda code. 

Any help would be greatly appreciated.

**Comment by bundyfx** [comment]
Hi @adamcoxon 

When you are updating ADF via the SAR, does the role that you are assuming have access to S3? Im guessing this is some error related to the role you are using when performing actions via the SAR.

**Comment by sbkok** [comment]
Thanks for reporting @adamcoxon.
I've talked with the team that is involved on this, wanted to share what we think will be the issue here, so others that run into the same know how to investigate.

I have upgraded from 2.1.2 to 3.0.4 multiple times, each time using administrator access though.

This could be related to:
- Your access credentials when you try to deploy the SAR, as @bundyfx mentioned.
- It could also be a SCP that is applied on the root organization account.

I think it must be either of these two, please keep us informed how it progresses.

**Comment by adamcoxon** [comment]
Hello @sbkok, @bundyfx,

Thanks for getting back to me on this with your suggestions. A few notes.

* When we initially deployed ADF via SAR we were using the Admin IAM user

* When we started the upgrade process via SAR we were using a specific role which has select permissions but does have read access to S3. 

* I have since logged back in with an Admin IAM user to try and get the stack to complete the rollback but this is having no effect and the stack continues to fail the update of the AWS::Serverless resources. 

* There are no SCPs attached the this account

I am now trying to continue the stack rollback process using advanced troubleshooting and skipping over the resources that continue to fail. Hopefully, then the stack will be rolled back and I can perform the upgrade via SAR with the admin account.

**Comment by adamcoxon** [comment]
Unfortunately, this did not work. I am able to get the stack to successfully rollback by skipping over the problematic resources but when I deploy again via SAR I get the same error messages listed above. I am now going to remove ADF and reinstall it as per the instructions in the admin doc.

**Comment by adamcoxon** [comment]
An uninstall and reinstall has worked very nicely and our ADF instance is back where it was as V3. After further research and raising a case with Enterprise Support, the only thing that may have caused this issue is that we used a different role to upgrade from when we initially deployed. 

Page 51 of this [SAR Doc](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-dg.pdf) details the error that we were getting.

A strange issue that I will know to look out for in the future.
