### ISSUE TITLE
parameter override through environment variables ?

### ISSUE THREAD

**Issue by amitsehgal** [awslabs/aws-deployment-framework#246]
Is there a plan to override parameters declared in global.yml through environment variables ?

**Comment by bundyfx** [comment]
Hi @amitsehgal - Could you please elaborate on what you are trying to solve?

Values in global can be populated from Parameter Store or other outputs from Cloudformation stacks currently but today it is not supported to have them defined from Environment Variables, this is something we could add though if there is some interest in it.

**Comment by amitsehgal** [comment]
here is an example .... --parameters below ... i would like to have that from env and not global.yml
or oveeride the one in global.yml with this flag.... something similar in when i run terraform i can override varables.tf value with TF_var_variablename
aws cloudformation create-stack  --stack-name startmyinstance  
    --template-body file://home/ec2-user/templates/startmyinstance.json 
    --parameters  ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro

**Comment by sbkok** [comment]
Hi @amitsehgal,

As described in the [user guide](https://github.com/awslabs/aws-deployment-framework/blob/master/docs/user-guide.md#parameter-injection), you can determine the value for parameters on the fly using intrinsic functions.
These can import values from CloudFormation outputs, retrieve parameter values, etc.

If I understand your request correctly, you want to be able to import the value using environment variables.
Would it help to have an intrinsic function that imports from the environment like this: "environment:SPECIFIC_ENV_VAR"?

If so, can you explain why the current intrinsic functions would not help in your use case?

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!

**Comment by amitsehgal** [comment]
@sbkok my bad...just saw the update and closure.... thanks for response... I had already found a workaround through ssm parameter .... however, could not find anything in cfn documentation about intrinsic function that can read from environments.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html . it works for me through ssm..thanks again..will keep you posted if anything.
