### ISSUE TITLE
Support for deploying SCPs to Organizational Units in ADF

### ISSUE THREAD

**Issue by thomasmcgannon** [awslabs/aws-deployment-framework#25]
It would be useful if you could deploy SCPs through the ADF.
I think as the bootstrap repository already supports an OU structure for deploying the bootstrap templates it could be enhanced to look for SCP policies in this structure and also deploy these to the OU.

I would see the new folder structure like:
```shell
.
├── adf-build/
├── adfconfig.yml
├── deployment/
├── example-adfconfig.yml
├── global.yml
├── readme.md
├── scp
│   ├── scprule1.scp
│   ├── scprule2.scp
│   └── scprule3.scp
├── team1
│   ├── global.yml
│   ├── lambda_codebase/
│   ├── regional.yml
│   ├── dev
│   │   ├── global.yml
│   │   ├── lambda_codebase/
│   │   ├── regional.yml
│   │   └── rules
│   └── rules
```

The SCP's would be stored separate to the org structure so that they can be re-used. Either in this repository as I have it in the **scp** directory, or perhaps a separate repository.

Then within each OU a **rules** file which would contain a list of policies which should be applied.

```shell
> cat team1/rules
scprule2.scp
scprule3.scp

> cat team1/dev/rules
scprule1.scp
```

**Comment by bundyfx** [comment]
Nice one, I think this will help users simplify the deployment of SCP across the organization. 

What would be your thoughts in regards to making the application of SCP's recursive, the same way we do base stacks? This would allow for a "base" SCP to be applied if a less specific one was specified up the file tree.

**Comment by thomasmcgannon** [comment]
I think just make use of SCP's own recursion, so the policy deployed through the framework only gets applied where specified and then let Organizations determine how this propagates down the OU structure.
