### ISSUE TITLE
CodePipeline Limitations forces max number of accounts per OU / Tag Target

### ISSUE THREAD

**Issue by StewartW** [awslabs/aws-deployment-framework#250]
I'm sure I've seen some chat about this before somewhere. But when using Tags  or OU accounts it becomes quite easy to hit the CodePipeline limits. (50 actions per stage) 

I'm curious if you have any ideas around this?  One potential avenue we're looking at is using a Lambda to co-ordinate the actions in each stage i.e rather than trying to have 60 Actions per Stage, having 1 lambda action trigger 60 different CodeBuild projects. 

Another approach we've taken is changing the logic in generate_pipeline_inputs to break larger OUs down into multiple Batches of 10/20 accounts etc.

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this limit is resolved with the release of Wave deployments as part of [release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues related to this feature.
