### ISSUE TITLE
Slack integration using AWS Chatbot

### ISSUE THREAD

**Issue by EdoBarroso** [awslabs/aws-deployment-framework#257]
Given the new features announced for CodeSuite [here](https://aws.amazon.com/about-aws/whats-new/2020/04/receive-notifications-for-aws-codebuild-codecommit-codedeploy-codepipeline-in-slack/), I believe it would be a good idea to replace the Slack integration method to this new one.

Thoughts?

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this feature has been [released as part of v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues related to this feature.
