### ISSUE TITLE
AWS CodeBuild image STANDARD_2_0 going EOL

### ISSUE THREAD

**Issue by EdoBarroso** [awslabs/aws-deployment-framework#267]
I just received an email saying that older CodeBuild images Ubuntu Standard 1.0, Ubuntu Standard 2.0 and Amazon Linux 2 Standard 1.0 will no longer be maintained.

As such, sample Deployment Maps should be updated to now use `STANDARD_3_0` instead of `STANDARD_2_0`, like [this one](https://github.com/awslabs/aws-deployment-framework/tree/master/samples/sample-cdk-app)

**Comment by sbkok** [comment]
Hi Eduaro,
Thanks for raising this. I thought I had replied to this but just realized I had not.
I am actively working on a new release where this will be fixed.
I will leave this ticket open until the release, so you will be notified immediately when it becomes available.
Kind regards, Simon
