### ISSUE TITLE
Configurable deployment OU

### ISSUE THREAD

**Issue by yawn** [awslabs/aws-deployment-framework#268]
As it says. Right now the name of the deployment OU is not configurable. Since Control Tower (for better or worse) is now the default account factory and introduces capitalised naming conventions (never mind that it uses whitespaces in it's Core accounts but forbids to use them in Service Catalogue). We should be able to match this.

**Comment by sbkok** [comment]
Unfortunately this would require a significant effort to change.

I'm closing this issue as it has been inactive for a long time. This probably means that it is no longer required to change this.
Please reopen if you still believe this would be relevant and worth the effort to refactor.

Thank you!
