### ISSUE TITLE
code deploy not working

### ISSUE THREAD

**Issue by anuprita87** [awslabs/aws-deployment-framework#286]
![image](https://user-images.githubusercontent.com/63067095/92141642-53345180-ee30-11ea-8076-3a35c3daeb95.png)
getting the error

[Container] 2020/09/03 16:25:19 Waiting for agent ping
--
2 | [Container] 2020/09/03 16:25:21 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2020/09/03 16:25:24 Phase is DOWNLOAD_SOURCE
4 | [Container] 2020/09/03 16:25:24 CODEBUILD_SRC_DIR=/codebuild/output/src277827710/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/covid19
5 | [Container] 2020/09/03 16:25:24 YAML location is /codebuild/output/src277827710/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/covid19/buildspec.yml
6 | [Container] 2020/09/03 16:25:24 Processing environment variables
7 | [Container] 2020/09/03 16:25:24 No runtime version selected in buildspec.
8 | [Container] 2020/09/03 16:25:24 Moving to directory /codebuild/output/src277827710/src/git-codecommit.us-east-1.amazonaws.com/v1/repos/covid19
9 | [Container] 2020/09/03 16:25:24 Registering with agent
10 | [Container] 2020/09/03 16:25:24 Phases found in YAML: 3
11 | [Container] 2020/09/03 16:25:24  PRE_BUILD: 6 commands
12 | [Container] 2020/09/03 16:25:24  BUILD: 5 commands
13 | [Container] 2020/09/03 16:25:24  POST_BUILD: 4 commands
14 | [Container] 2020/09/03 16:25:24 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
15 | [Container] 2020/09/03 16:25:24 Phase context status code:  Message:
16 | [Container] 2020/09/03 16:25:25 Entering phase INSTALL
17 | [Container] 2020/09/03 16:25:25 Phase complete: INSTALL State: SUCCEEDED
18 | [Container] 2020/09/03 16:25:25 Phase context status code:  Message:
19 | [Container] 2020/09/03 16:25:25 Entering phase PRE_BUILD
20 | [Container] 2020/09/03 16:25:25 Running command echo Logging in to Amazon ECR...
21 | Logging in to Amazon ECR...
22 |  
23 | [Container] 2020/09/03 16:25:25 Running command aws --version
24 | aws-cli/1.18.117 Python/3.8.3 Linux/4.14.186-110.268.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.17.40
25 |  
26 | [Container] 2020/09/03 16:25:31 Running command $(aws ecr get-login --no-include-email --region us-east-1)
27 | WARNING! Using --password via the CLI is insecure. Use --password-stdin.
28 | WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
29 | Configure a credential helper to remove this warning. See
30 | https://docs.docker.com/engine/reference/commandline/login/#credentials-store
31 |  
32 | Login Succeeded
33 |  
34 | [Container] 2020/09/03 16:25:34 Running command REPOSITORY_URI=897150306444.dkr.ecr.us-east-1.amazonaws.com/capstone
35 |  
36 | [Container] 2020/09/03 16:25:34 Running command COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION \| cut -c 1-7)
37 |  
38 | [Container] 2020/09/03 16:25:34 Running command IMAGE_TAG=${COMMIT_HASH:=latest}
39 |  
40 | [Container] 2020/09/03 16:25:34 Phase complete: PRE_BUILD State: SUCCEEDED
41 | [Container] 2020/09/03 16:25:34 Phase context status code:  Message:
42 | [Container] 2020/09/03 16:25:34 Entering phase BUILD
43 | [Container] 2020/09/03 16:25:34 Running command echo Build started on `date`
44 | Build started on Thu Sep 3 16:25:34 UTC 2020
45 |  
46 | [Container] 2020/09/03 16:25:34 Running command echo Building the Docker image...
47 | Building the Docker image...
48 |  
49 | [Container] 2020/09/03 16:25:34 Running command docker build -t $REPOSITORY_URI:latest .
50 | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
51 |  
52 | [Container] 2020/09/03 16:25:34 Command did not exit successfully docker build -t $REPOSITORY_URI:latest . exit status 1
53 | [Container] 2020/09/03 16:25:34 Phase complete: BUILD State: FAILED
54 | [Container] 2020/09/03 16:25:34 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker build -t $REPOSITORY_URI:latest .. Reason: exit status 1
55 | [Container] 2020/09/03 16:25:34 Entering phase POST_BUILD
56 | [Container] 2020/09/03 16:25:34 Running command echo Build completed on `date`
57 | Build completed on Thu Sep 3 16:25:34 UTC 2020
58 |  
59 | [Container] 2020/09/03 16:25:34 Running command echo Pushing the Docker images...
60 | Pushing the Docker images...
61 |  
62 | [Container] 2020/09/03 16:25:34 Running command docker push $REPOSITORY_URI:latest
63 | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
64 |  
65 | [Container] 2020/09/03 16:25:35 Command did not exit successfully docker push $REPOSITORY_URI:latest exit status 1
66 | [Container] 2020/09/03 16:25:35 Phase complete: POST_BUILD State: FAILED
67 | [Container] 2020/09/03 16:25:35 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker push $REPOSITORY_URI:latest. Reason: exit status 1

However my docker engine is running

ubuntu@ip-172-31-61-123:~/capstone17/pgpcc-capstone-covid$ docker build -t covid19 .
Sending build context to Docker daemon  8.757MB
Step 1/2 : FROM nginx:alpine
 ---> 6f715d38cfe0
Step 2/2 : COPY . /usr/share/nginx/html
 ---> Using cache
 ---> 7528fce4dfbe
Successfully built 7528fce4dfbe
Successfully tagged covid19:latest
ubuntu@ip-172-31-61-123:~/capstone17/pgpcc-capstone-covid$ docker tag covid19:latest 677469671329.dkr.ecr.us-east-1.amazonaws.com/covid19:latest
ubuntu@ip-172-31-61-123:~/capstone17/pgpcc-capstone-covid$ docker push 677469671329.dkr.ecr.us-east-1.amazonaws.com/covid19:latest
The push refers to repository [677469671329.dkr.ecr.us-east-1.amazonaws.com/covid19]
b42136208ab2: Layer already exists
6ad8d562c843: Layer already exists
425ee8569962: Layer already exists
5d9ee84be1ec: Layer already exists
6bcd003260b2: Layer already exists
50644c29ef5a: Layer already exists
latest: digest: sha256:c8942ada9324e523d487378d36397f249d9d0

**Comment by sbkok** [comment]
Hi @anuprita87,

The error reports that it is not able to connect to Docker, most likely the CodeBuild environment is not running with privilege mode on. This is required in order to use Docker inside a CodeBuild environment. To enable this, you need to set the `privileged` boolean property to True in the CodeBuild provider properties. Like this:

```yaml
  - name: # Some project name
    default_providers:
      # ....
      build:
        provider: codebuild
        properties:
          privileged: True
      # .....
```

I hope this fixes the issue for you. If not, could you share the deployment map and buildspec used by CodeBuild?

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases). Thank you.
