### ISSUE TITLE
Multiple Pipelines with Slack Notifications breaks pipeline Generation

### ISSUE THREAD

**Issue by StewartW** [awslabs/aws-deployment-framework#297]
### Issue
We've recently hit a snag with around 45 pipelines. 
When trying to create a new pipeline with SlackNotifications it fails due to the max policy size being exceeded. 
This is because the adf-notifications construct is trying to add permissions the the Slack Notification Lambdas resource policy. 

I'm currently looking at resolving this using the AWS ChatBot. If the solution works, I'm happy to add it back to the upstream. 
This would also close issue #257. 

### Suggested Fix: 
In order to fix this, I'm proposing changing the notification_endpoint schema definition to contain a type. 
Initial types would be "Lambda | ChatBot". The accepted values would be "email / slack channel" for the lambda or "Channel Configuration" for the ChatBot. 

 At the moment, given the lack of a boto3 api, I don't think there's a reasonable way to automate the creation of the slack channel configurations as part of ADF. However if there's any suggestion here, I'm happy to consider them.

**Comment by dsudduth** [comment]
@StewartW Any fixes (even temporary)? We're not using Slack notifications, but still met this exact error.

**Comment by StewartW** [comment]
> @StewartW Any fixes (even temporary)? We're not using Slack notifications, but still met this exact error.
Let me see if I can't create a gist with a workaround. Aye you just using the standard SES email notification?

**Comment by dsudduth** [comment]
> > @StewartW Any fixes (even temporary)? We're not using Slack notifications, but still met this exact error.
> 
> 
> 
> Let me see if I can't create a gist with a workaround. Aye you just using the standard SES email notification? 
> 
> 

Hi Stewart,

That would be awesome! I am using the the standard email notifications.

**Comment by StewartW** [comment]
> > > @StewartW Any fixes (even temporary)? We're not using Slack notifications, but still met this exact error.
> > 
> > 
> > Let me see if I can't create a gist with a workaround. Aye you just using the standard SES email notification?
> 
> Hi Stewart,
> 
> That would be awesome! I am using the standard email notifications.

https://gist.github.com/StewartW/986a3bfe82e65df521875ed92ee472c2 

So (I had only assumed that this was related to Slack notifications) 
The Gist above will fix this if you only use email notifications because it won't add the policy to the topic for every pipeline that you create. 
The problem is the ```  _topic.add_to_resource_policy(_statement) ``` being invoked everytime. 

It should be a simple enough drop in replacement for the adf_notifications.Notifications class. 
This lives in (**aws-deployment-framework-bootstrap/adf-build/shared/cdk/cdk_constructs/adf_notifications.py**)

**Comment by dsudduth** [comment]
Thank you @StewartW! This is incredibly helpful. I'll apply this until we can permanently fix Slack. The good news for the client is they are just using email at the moment. Thanks for lending a hand!

**Comment by engrun** [comment]
Just bumped into this today (using Slack).  Not much activity on this issue, so I guess there is still no fix for this?

**Comment by StewartW** [comment]
> Just bumped into this today (using Slack). Not much activity on this issue, so I guess there is still no fix for this?

There's a [PR here](https://github.com/awslabs/aws-deployment-framework/pull/367) that remedies this issue by using ChatBot.

**Comment by engrun** [comment]
Thanks for the pointer.  Do we know when this PR will be merged (and released)?

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this feature has been [released as part of v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
Please open a new issue if you are experiencing any issues related to this feature.
