### ISSUE TITLE
ADF CodeBuild is still on version 2.0

### ISSUE THREAD

**Issue by kerimk06** [awslabs/aws-deployment-framework#300]
Is it possible to change the ADF CodeBuild version to 3.0 because the 2.0 version is not longer supported

**Comment by sbkok** [comment]
Hi Kirim,

Thanks for raising this.
I'm working on a new branch that will be released shortly where this is fixed.
I will leave this issue open until that release is out, so you will be made aware immediately when it is ready.

Kind regards, Simon

* Related to issue #267
