### ISSUE TITLE
Deploy outside organization

### ISSUE THREAD

**Issue by kerimk06** [awslabs/aws-deployment-framework#304]
Is there a way to deploy to an account outside the ADF organization? Even if you have to make a couple of changes in the ADF code?

**Comment by kerimk06** [comment]
Found out it is possible with a couple of changes: https://github.com/awslabs/aws-deployment-framework/pull/309

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a long time. Please reopen if you need this feature, if so +1. Also please reopen if you are planning to contribute this feature / finish PR #309.

Thank you!
