### ISSUE TITLE
CodePipeline API is updating, any consequences?

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#310]
Hello!

We received this warning from AWS:

> AWS CodePipeline is updating the StageExecution, PipelineExecution and PipelineExecutionSummary objects returned by GetPipelineState, GetPipelineExecution and ListPipelineExecutions APIs to better reflect the status of pipeline executions impacted when updating a pipeline definition.

Does this have any effect on ADF?

**Comment by sbkok** [comment]
Thanks for raising this! I checked the code base of v2.1.2 and v3.0.0 to v3.0.6, these versions are not affected by this change.
I hope this answers your question. Feel free to close the issue if it did, or raise any follow-up questions/concerns if you have any.

**Comment by hynynen** [comment]
Thank you for your effort!
