### ISSUE TITLE
I have this problem with deployment account 

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#317]
![image](https://user-images.githubusercontent.com/77515163/104981809-a0911400-5a09-11eb-9d0d-b6b16ab8596d.png)
Can you help me please to fix this prbolme?
When i bring out/in from( deployment OU) my step function failed with the error:
![image](https://user-images.githubusercontent.com/77515163/104982007-0087ba80-5a0a-11eb-9a0f-7c990aeef632.png)
some solution please?

**Comment by StewartW** [comment]
The error suggests you have a problem with your notification endpoint. Looks like it's missing?

**Comment by 20FS21** [comment]
I try to put my deployment account out from the OU deployment, wait some minutes that step function finish his job.
After this re put the deployment account in the the deployment OU.
For magic everything start to work after this.

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases). Thank you!
