### ISSUE TITLE
S3 ETL fails when "Build: enabled: False

### ISSUE THREAD

**Issue by psgivens** [awslabs/aws-deployment-framework#318]
An example such as the following fails because the source output artifact doesn't match the deploy input artifact. I've provided the solution in this ticket. 

    - name: sample-s3-pipeline
      default_providers:
        source:
          provider: s3
          properties:
            bucket_name: packer-bucket-test
            object_key: input.zip
            account_id: 44444444444444
        build:
          enabled: False # if you wish to disable the build phase in a pipeline
        deploy:
          provider: s3
      targets:
        - target: 222222222222
          properties:
            bucket_name: test-adf-bucket-eu
            object_key: output.zip

[S3 output artifact is "output-source".](
https://github.com/awslabs/aws-deployment-framework/blob/31f4719f83e80bd165b1567fed27de8eff090460/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py#L324)

        if self.category == 'Source':
            action_props["output_artifacts"] = [
                _codepipeline.CfnPipeline.OutputArtifactProperty(
                    name="output-source"
                )
            ]

[When Build is set to "enabled: false", CodeBuild is skipped and the S3 deploy's input artifact is "{0}-build".format(self.map_params['name']](https://github.com/awslabs/aws-deployment-framework/blob/31f4719f83e80bd165b1567fed27de8eff090460/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py#L305)

        if self.category == 'Deploy':
            action_props["input_artifacts"] = [
                _codepipeline.CfnPipeline.InputArtifactProperty(
                    name="{0}-build".format(self.map_params['name'])
                )
            ]

The generated CloudFormation for the pipeline fails with a complaint that there isn't an output format for "{0}-build". 

**Solution**: Add a build the following block when [building the Deploy action after the initial set block.](https://github.com/awslabs/aws-deployment-framework/blob/31f4719f83e80bd165b1567fed27de8eff090460/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py#L311). 

            if not self.map_params.get('default_providers', {}).get('build', {}).get('enabled', True):
                action_props["input_artifacts"] = [
                    _codepipeline.CfnPipeline.InputArtifactProperty(
                        name="output-source"
                    )
                ]

**Comment by sbkok** [comment]
I'm working on a fix for this problem, will update once it is ready.
