### ISSUE TITLE
Support template_filenames in ADF

### ISSUE THREAD

**Issue by TharaldBye** [awslabs/aws-deployment-framework#319]
ADF supports a custom template_filename. 
We would really like support for template_filenames in deployment map. 

We want to avoid the monorepo sample approach because it triggers all pipelines on every change.

To avoid many pipelines we create a single SAM stack with all serverless and cloudformation resources. 
The problem with this approach is that we end up with a single cloudformation stack with many resources.

A better and cleaner solution would be to output many cloudformation templates from the codebuild step.
ADF could process template_files and perform a cloudformation deploy action for every template file listed.
This way we would end up with several small stacks deployed from 1 ADF pipeline.

**Comment by TharaldBye** [comment]
I attempted to use template_filename in deployment map as suggested (alternative 3) https://github.com/awslabs/aws-deployment-framework/issues/315. ADF SAM does not seem to support template_filename.

I was able to solve this problem by using root_dir and stack_name is deployment map. 
deployment map:
targets:
  - path: [123456] # account number
    properties:
      stack_name: my-stack-1
      root_dir: project-root-dir/folder-1
  - path: [123456] # account number
    properties:
      stack_name: my-stack-2
      root_dir: project-root/folder-2

In buildspec.yml:
1. if using CDK -> synth cdk stack to generate cloudformation template (folder-1 template)
2. run package_transform.sh on template. 
3. copy params and SAM template to folder-1.
4. Repeat for folder-2: cdk synth, ADF transform and copy files.

5.Export artifacts:
artifacts:
  files:
    - '$INFRASTRUCTURE_ROOT_DIR/folder-1/params/*'
    - '$INFRASTRUCTURE_ROOT_DIR/folder-1/template_eu-west-1.yml'
    - '$INFRASTRUCTURE_ROOT_DIR/folder-2/params/*'
    - '$INFRASTRUCTURE_ROOT_DIR/folder-2/template_eu-west-1.yml'

**Comment by innokenty** [comment]
## Problem

Trying to use this functionality and running into the following issue:

`package_transform.sh` is not applied on template files other than `template.yml` and in fact it doesn't support customization of template name at all. [See source code](https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/package_transform.sh#L54): `template.yml` filename is simply hardcoded in the script.

This makes it impossible to use this approach for templates that use child-templates (which is often the case).

## Proposal

Add  a parameter to `package_transform.sh` to allow controlling target template filename (defaults to `template.yml`), hence allowing to manually add a build command to transform another template file, that is used in deployment.

Something like:
```
  build:
    commands:
      - bash adf-build/helpers/package_transform.sh
      - bash adf-build/helpers/package_transform.sh --template another_template.yml
```

### P.S.
Is anyone reading this?
