### ISSUE TITLE
ADF Bootstrap don't delete my Default VPC

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#321]
Hello,
When i create and import new account in bootstrap I use:

accounts:
  - account_full_name: XXXXX
    organizational_unit_path: /repository
    email: XXXXX@XXXx
    allow_billing: False
    delete_default_vpc: True
    alias: 
    tags:
      - created_by: adf

Can you explain me why after deploy I see in my all account the default VPC?
Thanks a lot.

**Comment by 20FS21** [comment]
Team do you have some suggest for fix this problem ? :-(

**Comment by deltagarrett** [comment]
Hi @20FS21 , would you be so kind to share what is the log of the bootstrap pipeline? This is the pipeline that take care of this deletion.

**Comment by 20FS21** [comment]
Hello @deltagarrett ,
In my bootstrap pipeline logs i have some private data :-(
could you kindly say me exactly witch part of it do you need.
For you information the final result of my pipeline is good:


[Container] 2021/01/27 01:43:38 Phase complete: BUILD State: SUCCEEDED
--
178 | [Container] 2021/01/27 01:43:38 Phase context status code:  Message:
179 | [Container] 2021/01/27 01:43:38 Entering phase POST_BUILD
180 | [Container] 2021/01/27 01:43:38 Phase complete: POST_BUILD State: SUCCEEDED
181 | [Container] 2021/01/27 01:43:38 Phase context status code:  Message:


![image](https://user-images.githubusercontent.com/77515163/106044054-84633600-60df-11eb-91c4-9972c8b0778f.png)

**Comment by 20FS21** [comment]
@deltagarrett do you find some solution for this case ;-)

**Comment by deltagarrett** [comment]
Hi @20FS21 , 

are you saving .yml files inside the adf-bootstrap/adf-accounts folder? Structure should be something like 

```
adf-accounts
├── core.yml
├── deployment.yml
├── master.yml
├── readme.md
└── sandbox.yml
```

and in the log you should see all the VPC ADF is finding and trying to delete. Can you confirm bootstrap repo is configured as above? If yes, we can dive deep a bit more.

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!
