### ISSUE TITLE
adf-accounts / allow_billing usage

### ISSUE THREAD

**Issue by lpipiska** [awslabs/aws-deployment-framework#323]
Hi all

I would like to have your clarification on allow_billing setting. 

Whatever we set here the only value which applies is the one which was provided at the account creation. updating the value afterwards does not seem to have any impact.
Eg: At the account creation (initial bootstrap) the setting was false. The Billing dashboard is not accessible and reports IAM permission issue. After changing this value to True nothing has happened/changed. 

Can you please clarify how is this supposed to work? Is this meant to be used as a one time set up parameter at the account creation/bootstrap or do we face a bug here? 

Unfortunately documentation for this is bit skinny so we cannot figure out expected behavior of this parameter.

Thank you

**Comment by StewartW** [comment]
It's used as part of the Organisations API call  here: 
https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py#L331 

As part of the [create_account boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.create_account) call 

I can't see an equivalent API for updating it (And I think that has to be done by the root account in the desired account.) So I suspect it won't be an easy change.

**Comment by lpipiska** [comment]
Thanks for clear answer. Closing the issue now
