### ISSUE TITLE
Deprecating botocore.vendored.requests

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#324]
Hello!

We have been receiving this warnings. How is this affected to ADF? We had advise:
Lambda function must be "refreshed" so that it pulls the latest version of cfnresponse.
"If you are using the cfn-response module for a Lambda-backed custom resource, you must modify your Lambda function resource’s Code or Runtime property and update your stack(s) in order to get the latest version of the cfn-response module which removed its dependency on botocore.requests."

Do we need to manually update ADF Lambdas somehow? Any new releases coming out before April 1st?

**Comment by engrun** [comment]
Good catch @hynynen .  Hopefully ADF is not affected

**Comment by sbkok** [comment]
Hi @hynynen,

Thanks for raising this as an issue.
I've checked the code that we depend on and found one reference.
Luckily this was in the samples folder, the sample-expunge-vpc one to be precise.

I have created a fix for this and will open that as a separate PR.

Best regards, Simon
