### ISSUE TITLE
Basic GovCloud Support

### ISSUE THREAD

**Issue by dsudduth** [awslabs/aws-deployment-framework#332]
# GovCloud Support

## Summary

This feature request would provide basic support for GovCloud regions by adjusting partitions throughout templates and the code base to leverage the `${AWS::Partition}` [pseudo parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html). It would also add conditional statements for services that do not exist in GovCloud. *i.e., Tagging Policies*.

## Motivation

GovCloud customers are looking for a robust CI/CD framework based on AWS native tooling. ADF is one of the most feature rich options. With small changes this framework could easily be adapted to support a wider audience.

## In Scope

- Modify the code base to support the `arn:aws-us-gov` GovCloud partition.
- Provide support for the `us-gov-west-1` region as  a primary install location.
- Avoid failures due to missing features in GovCloud. The only item identified in the code base is Tagging Policies.

## Out of Scope

**Account Vending in GovCloud** - Account vending in GovCloud requires accounts to be created in commercial regions and linked. The changes needed to support this would be significant and will not be addressed by this feature.

## References

- [ARN Resource Names](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html)
- [Pseudo Parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html)

**Comment by sbkok** [comment]
Thanks for submitting this request @dsudduth!
I'm looking into the required steps and will reach out to you directly to sync up.

**Comment by OlafConijn** [comment]
interesting! we are currently building govcloud support in org-formation (https://github.com/org-formation/org-formation-cli). if you find it interesting feel free to ping me and we can compare noted. easiest way to do so is over the org-formation slack (https://join.slack.com/t/org-formation/shared_invite/enQtOTA5NjM3Mzc4ODUwLTMxZjYxYzljZTE5YWUzODE2MTNmYjM5NTY5Nzc3MzljNjVlZGQ1ODEzZDgyMWVkMDg3Mzk1ZjQ1ZjM4MDhlOGM).

**Comment by dsudduth** [comment]
Hi @OlafConijn! Thanks for sharing your tool. Looks great! I'll connect with you on Slack. Any tool that can work across commercial and GovCloud is of interest.

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this feature has been [released as part of v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues related to this feature.
