### ISSUE TITLE
aws-deployment-framework-base-templates for New Account failed. What could be the problem?

### ISSUE THREAD

**Issue by anetoo** [awslabs/aws-deployment-framework#339]
![image](https://user-images.githubusercontent.com/16065858/111896809-14d83b80-89ea-11eb-92cc-be7533cdcb0c.png)

1 | [Container] 2021/03/21 05:47:27 Waiting for agent ping
-- | --
2 | [Container] 2021/03/21 05:47:29 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2021/03/21 05:47:30 Phase is DOWNLOAD_SOURCE
4 | [Container] 2021/03/21 05:47:30 CODEBUILD_SRC_DIR=/codebuild/output/src352255631/src
5 | [Container] 2021/03/21 05:47:30 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2021/03/21 05:47:30 No commands found for phase name: install
7 | [Container] 2021/03/21 05:47:30 Processing environment variables
8 | [Container] 2021/03/21 05:47:31 Selecting 'python' runtime version '3.8' based on manual selections...
9 | [Container] 2021/03/21 05:47:31 Running command echo "Installing Python version 3.8 ..."
10 | Installing Python version 3.8 ...
11 |  
12 | [Container] 2021/03/21 05:47:31 Running command pyenv global  $PYTHON_38_VERSION
13 |  
14 | [Container] 2021/03/21 05:47:31 Moving to directory /codebuild/output/src352255631/src
15 | [Container] 2021/03/21 05:47:31 Registering with agent
16 | [Container] 2021/03/21 05:47:31 Phases found in YAML: 3
17 | [Container] 2021/03/21 05:47:31  BUILD: 6 commands
18 | [Container] 2021/03/21 05:47:31  INSTALL: 0 commands
19 | [Container] 2021/03/21 05:47:31  PRE_BUILD: 2 commands
20 | [Container] 2021/03/21 05:47:31 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
21 | [Container] 2021/03/21 05:47:31 Phase context status code:  Message:
22 | [Container] 2021/03/21 05:47:31 Entering phase INSTALL
23 | [Container] 2021/03/21 05:47:31 Phase complete: INSTALL State: SUCCEEDED
24 | [Container] 2021/03/21 05:47:31 Phase context status code:  Message:
25 | [Container] 2021/03/21 05:47:31 Entering phase PRE_BUILD
26 | [Container] 2021/03/21 05:47:31 Running command pip install -r adf-build/requirements.txt --quiet
27 |  
28 | [Container] 2021/03/21 05:48:01 Running command pytest -vvv
29 | ============================= test session starts ==============================
30 | platform linux -- Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /root/.pyenv/versions/3.8.8/bin/python3.8
31 | cachedir: .pytest_cache
32 | rootdir: /codebuild/output/src352255631/src, configfile: pytest.ini, testpaths: adf-build/tests, adf-bootstrap/deployment/lambda_codebase/tests
33 | collecting ... collected 21 items
34 |  
35 | adf-build/tests/test_config.py::test_validation PASSED                   [  4%]
36 | adf-build/tests/test_config.py::test_validation_list_deployment_target PASSED [  9%]
37 | adf-build/tests/test_config.py::test_validation_list_deployment_account_target PASSED [ 14%]
38 | adf-build/tests/test_config.py::test_raise_validation_remove_moves PASSED [ 19%]
39 | adf-build/tests/test_config.py::test_raise_validation_remove_roles PASSED [ 23%]
40 | adf-build/tests/test_config.py::test_raise_validation_remove_deployment_target_region PASSED [ 28%]
41 | adf-build/tests/test_config.py::test_raise_validation_length_deployment_target_region PASSED [ 33%]
42 | adf-build/tests/test_config.py::test_raise_validation_organizations_scp PASSED [ 38%]
43 | adf-build/tests/test_main.py::test_is_account_valid_state PASSED         [ 42%]
44 | adf-build/tests/test_main.py::test_is_account_in_invalid_state PASSED    [ 47%]
45 | adf-build/tests/test_main.py::test_is_account_is_in_root PASSED          [ 52%]
46 | adf-build/tests/test_main.py::test_ensure_generic_account_can_be_setup PASSED [ 57%]
47 | adf-build/tests/test_main.py::test_update_deployment_account_output_parameters PASSED [ 61%]
48 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_extract_message PASSED [ 66%]
49 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_extract_pipeline PASSED [ 71%]
50 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_is_approval PASSED [ 76%]
51 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_is_bootstrap PASSED [ 80%]
52 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_create_approval PASSED [ 85%]
53 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_create_pipeline_message_text PASSED [ 90%]
54 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_create_bootstrap_message_text PASSED [ 95%]
55 | adf-bootstrap/deployment/lambda_codebase/tests/test_slack.py::test_create_bootstrap_message_fail_text PASSED [100%]
56 |  
57 | ============================== 21 passed in 1.00s ==============================
58 |  
59 | [Container] 2021/03/21 05:48:03 Phase complete: PRE_BUILD State: SUCCEEDED
60 | [Container] 2021/03/21 05:48:03 Phase context status code:  Message:
61 | [Container] 2021/03/21 05:48:03 Entering phase BUILD
62 | [Container] 2021/03/21 05:48:03 Running command sam build -t adf-bootstrap/deployment/global.yml
63 |  
64 | SAM CLI now collects telemetry to better understand customer needs.
65 |  
66 | You can OPT OUT and disable telemetry collection by setting the
67 | environment variable SAM_CLI_TELEMETRY=0 in your shell.
68 | Thanks for your help!
69 |  
70 | Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html
71 |  
72 | Building codeuri: lambda_codebase/ runtime: python3.8 metadata: {} functions: ['SendSlackNotification', 'EnableCrossAccountAccess', 'CheckPipelineStatus']
73 | Running PythonPipBuilder:ResolveDependencies
74 | Running PythonPipBuilder:CopySource
75 | Building codeuri: lambda_codebase/initial_commit runtime: python3.8 metadata: {} functions: ['InitialCommitHandler']
76 | Running PythonPipBuilder:ResolveDependencies
77 | Running PythonPipBuilder:CopySource
78 |  
79 | Build Succeeded
80 |  
81 | Built Artifacts  : .aws-sam/build
82 | Built Template   : .aws-sam/build/template.yaml
83 |  
84 | Commands you can use next
85 | =========================
86 | [*] Invoke Function: sam local invoke
87 | [*] Deploy: sam deploy --guided
88 |  
89 |  
90 | [Container] 2021/03/21 05:48:07 Running command sam package --output-template-file adf-bootstrap/deployment/global.yml --s3-prefix adf-bootstrap/deployment --s3-bucket $DEPLOYMENT_ACCOUNT_BUCKET
91 |  
92 | Uploading to adf-bootstrap/deployment/1b8950beec69bba7a3e84450a47a276e  106063 / 106063.0  (100.00%)
93 |  
94 | Uploading to adf-bootstrap/deployment/95376ad45ac695ad03bcb1955e15b212  16164 / 16164.0  (100.00%)
95 |  
96 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  262144 / 7904873.0  (3.32%)
97 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  524288 / 7904873.0  (6.63%)
98 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  786432 / 7904873.0  (9.95%)
99 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  1048576 / 7904873.0  (13.26%)
100 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  1310720 / 7904873.0  (16.58%)
101 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  1572864 / 7904873.0  (19.90%)
102 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  1835008 / 7904873.0  (23.21%)
103 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  2097152 / 7904873.0  (26.53%)
104 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  2359296 / 7904873.0  (29.85%)
105 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  2621440 / 7904873.0  (33.16%)
106 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  2883584 / 7904873.0  (36.48%)
107 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  3145728 / 7904873.0  (39.79%)
108 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  3407872 / 7904873.0  (43.11%)
109 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  3670016 / 7904873.0  (46.43%)
110 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  3932160 / 7904873.0  (49.74%)
111 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  4194304 / 7904873.0  (53.06%)
112 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  4456448 / 7904873.0  (56.38%)
113 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  4718592 / 7904873.0  (59.69%)
114 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  4980736 / 7904873.0  (63.01%)
115 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  5242880 / 7904873.0  (66.32%)
116 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  5505024 / 7904873.0  (69.64%)
117 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  5767168 / 7904873.0  (72.96%)
118 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  6029312 / 7904873.0  (76.27%)
119 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  6291456 / 7904873.0  (79.59%)
120 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  6553600 / 7904873.0  (82.91%)
121 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  6815744 / 7904873.0  (86.22%)
122 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  7077888 / 7904873.0  (89.54%)
123 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  7340032 / 7904873.0  (92.85%)
124 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  7602176 / 7904873.0  (96.17%)
125 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  7864320 / 7904873.0  (99.49%)
126 | Uploading to adf-bootstrap/deployment/536972a518a67c7718beb71936dd592c  7904873 / 7904873.0  (100.00%)
127 | Successfully packaged artifacts and wrote output template to file adf-bootstrap/deployment/global.yml.
128 | Execute the following command to deploy the packaged template
129 | sam deploy --template-file /codebuild/output/src352255631/src/adf-bootstrap/deployment/global.yml --stack-name <YOUR STACK NAME>
130 |  
131 |  
132 |  
133 | [Container] 2021/03/21 05:48:12 Running command aws s3 sync ./adf-build/shared s3://$DEPLOYMENT_ACCOUNT_BUCKET/adf-build --quiet
134 |  
135 | [Container] 2021/03/21 05:48:13 Running command aws s3 sync . s3://$S3_BUCKET --quiet --delete
136 |  
137 | [Container] 2021/03/21 05:48:20 Running command python adf-build/main.py
138 | 2021-03-21 05:48:20,908 \| INFO \| __main__ \| ADF Version 3.1.2 \| (main.py:235)
139 | 2021-03-21 05:48:20,908 \| INFO \| __main__ \| ADF Log Level is INFO \| (main.py:236)
140 | 2021-03-21 05:48:21,437 \| INFO \| organization_policy \| Determining if Organization Policy changes are required. (Tagging or Service Controls) \| (organization_policy.py:96)
141 | 2021-03-21 05:48:24,958 \| INFO \| organizations \| SERVICE_CONTROL_POLICY are currently enabled within the Organization \| (organizations.py:49)
142 | 2021-03-21 05:48:25,351 \| INFO \| organizations \| TAG_POLICY are currently enabled within the Organization \| (organizations.py:49)
143 | Traceback (most recent call last):
144 | File "/codebuild/output/src352255631/src/adf-build/shared/python/cloudformation.py", line 187, in _create_change_set
145 | self.client.create_change_set(
146 | File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
147 | return self._make_api_call(operation_name, kwargs)
148 | File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
149 | raise error_class(parsed_response, operation_name)
150 | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Unable to fetch parameters [kms_arn] from parameter store for this account.
151 |  
152 | The above exception was the direct cause of the following exception:
153 |  
154 | Traceback (most recent call last):
155 | File "adf-build/main.py", line 348, in <module>
156 | main()
157 | File "adf-build/main.py", line 286, in main
158 | cloudformation.create_stack()
159 | File "/codebuild/output/src352255631/src/adf-build/shared/python/cloudformation.py", line 277, in create_stack
160 | create_change_set = self._create_change_set()
161 | File "/codebuild/output/src352255631/src/adf-build/shared/python/cloudformation.py", line 206, in _create_change_set
162 | raise GenericAccountConfigureError(error) from error
163 | errors.GenericAccountConfigureError: An error occurred (ValidationError) when calling the CreateChangeSet operation: Unable to fetch parameters [kms_arn] from parameter store for this account.
164 |  
165 | [Container] 2021/03/21 05:48:27 Command did not exit successfully python adf-build/main.py exit status 1
166 | [Container] 2021/03/21 05:48:27 Phase complete: BUILD State: FAILED
167 | [Container] 2021/03/21 05:48:27 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: python adf-build/main.py. Reason: exit status 1
168 | [Container] 2021/03/21 05:48:27 Entering phase POST_BUILD
169 | [Container] 2021/03/21 05:48:27 Phase complete: POST_BUILD State: SUCCEEDED
170 | [Container] 2021/03/21 05:48:27 Phase context status code:  Message:

**Comment by StewartW** [comment]
Can you check your state machine in the bill paying account please? 
Your bootstrap template is failing when looking for the kms_arn ssm param. (Can you confirm if it exists in the deployment region as well)

This should be created when an account is bootstrapped.

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!
