### ISSUE TITLE
No module named jinja2 during upgrade to 3.1.2 (question around behavior)

### ISSUE THREAD

**Issue by rickardl** [awslabs/aws-deployment-framework#373]
Hi,

I encountered an issue upgrading to the latest version of 3.1.2, in our deployment of ADF, using an internal repo.

## Problem

I encountered a strange anomaly when upgrading from `3.0.6` to `3.1.2`, in regards to a number of Custom Resources that failed during deployment, related to their Lambda handlers failing to find their dependencies. I got assistance from AWS Support (Case #8579420561) to identity the root cause and it seems like #56 changed the behavior.

During our upgrade we encountered an error `No module named jinja2`, and later the same errors for `cfn_custom_resource` during our deployment with SAM.

During troubleshooting we fail to identity how the [lambdas](https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/) are able to call their dependencies, since I can't understand where they are being fetched or provided.

## Solution

Right now, we modified the Cloudformation template for the SAM application to contain a reference to our custom lambda layer, where we include the above dependencies, that seemed to solve our imminent issue

## Question

Is this by design? I would expect the above modules to be available through a shared lambda layer, used by each lambda. This would mimic the behavior provided by `shared_layer` (although that one doesn't include third-party modules).

Would it be possible to elaborate on how this works, we're more than willing to move away from this mitigation (even though I feel lambda layers is being promoted for this use case, so it's a bit confusing).

**Comment by sbkok** [comment]
Hi @rickardl,

Thanks for reporting this.
I've looked into our changes since 3.0.6, we did upgrade from Jinja2 v2.10.1 to v2.11.2 + moved from Python v3.7 to v3.8.
Due to time restrictions, I have not been able to reproduce a similar scenario to upgrade from v3.0.6.
We will reach out to you directly to investigate what happened.
I will post updates on this issue once we know more.

Best regards,
Simon

**Comment by rickardl** [comment]
Hi,

I'm closing this as the SAR package is working correctly when deployed.

It seems I had some issues with the SAM deployment locally from my version of ADF, that prevented the inclusion of some of the required payloads, when deploying directly from the SAR repository it packaged the InitialCommit function correctly, it now includes all the required dependencies.

Likely caused by my own environment, if you're attempting to build or package ADF, it should be done in a container locally to avoid this. 

Thanks for the assistance @kalleeh @sbkok!

**Comment by rickardl** [comment]
Hi,

It seems I had some issues with the SAM deployment locally from my version of ADF, that prevented the inclusion of some of the required payloads, when deploying directly from the SAR repository it packaged the BootstrapCreateInitialCommitFunction correctly, it now includes all the required dependencies
