### ISSUE TITLE
ADF Pipeline creation fails if target account starts with zero

### ISSUE THREAD

**Issue by at7925** [awslabs/aws-deployment-framework#38]
aws-deployment-framework-pipelines fails with error "Unknown definition for target” if target account Id starts with 0 (zero)

Following example fails for account 011111111111

*deployment_map.yml*
```
---
pipelines:
  - name: org-vpc
    type: cc-cloudformation
    params:
      - SourceAccountId: 555555555555
    targets:
      - 999999999999 # Sandbox009
      - 011111111111 # Sandbox001
```
Log:
```
Traceback (most recent call last):
File "./adf-build/generate_pipelines.py", line 155, in <module>
main()
File "./adf-build/generate_pipelines.py", line 122, in main
pipeline_target.fetch_accounts_for_target()
File "/codebuild/output/src340903710/src/adf-build/target.py", line 118, in fetch_accounts_for_target
raise InvalidDeploymentMapError("Unknown defintion for target: {0}".format(self.path))
errors.InvalidDeploymentMapError: Unknown defintion for target: 6102444452
[Container] 2019/04/24 19:02:22 Command did not exit successfully python ./adf-build/generate_pipelines.py exit status 1
[Container] 2019/04/24 19:02:22 Phase complete: BUILD State: FAILED
```

Please also note: the error message  "Unknown definition for target: 6102444452" does not reference to 011111111111 but some other number, it makes difficult to find a problem when deployment_map.yml has may pipelines

**Comment by bundyfx** [comment]
Hi @at7925 Thanks for reporting this bug!

I'll dig into this one, it must be something going with the parsing of the integer and cutting of the leading 0. I will attempt to replicate this asap! 

Thanks again!

**Comment by bundyfx** [comment]
Hello @at7925 - I tested this again and was not able to reproduce the error. I also created a unit test with a stub AWS Account Id that starts with a leading 0 and I do not get any error when loading and parsing the value *(I noticed tho it gets parsed as a string)*. I will continue having a look into this but the issue may of been solved by updating to pyyaml > 5.1 which is what ADF is using as of #40.

**Comment by at7925** [comment]
Hi Flynn, 
I am glad that the problem is not reproducible in the new ADF release (v0.3.0). Also setting up a test with account with leading zero is pretty good idea.
We will upgrade ADF in a week, hopefully the issue will not happen after that.
Meanwhile you can close issue as fixed, I may re-open it if problem appears after upgrade again
Thank you,
Alex

**Comment by bundyfx** [comment]
Perfect, happy to dig into this more if you notice it come up again. Cheers!
