### ISSUE TITLE
Account bootstrap occasionally fails due to race condition

### ISSUE THREAD

**Issue by tylergohl** [awslabs/aws-deployment-framework#383]
# Account bootstrap process occasionally fails due to race condition
## Summary
Occasionally the bootstrapping process for new accounts will fail due to what appears to be a race condition and the eventual consistency nature of organizations.  I was able to reliably reproduce this in GovCloud - however I'm not sure if the same issue exists in commercial.  When new accounts join an organization (at least in GovCloud) there is a 10-20 minute period where IAM requests against S3 (and presumably other resources) that use the `aws:PrincipalOrgID` condition key will intermittently fail.  The request failure percentage starts off high immediately after the account joins the organization and slowly improves over 10-20 minutes until no more failures are observed.
 
## Steps to reproduce
* Create a new account manually
* Join the account to an organization
* Move the account to a new OU (to kick off bootstrap process) immediately
* You may receive an `InvalidTemplateError` or `GenericAccountConfigureError` mentioning you don't have access to the bootstrap template bucket.  Example:

```
Error": "InvalidTemplateError",
    "Cause": "{\"errorMessage\": \"https://s3-us-gov-west-1.amazonaws.com/serverlessrepo-aws-deplo-bootstraptemplatesbucket-1xzui6o5xuvig/adf-bootstrap/global.yml: An error occurred (ValidationError) when calling the ValidateTemplate operation: S3 error: Access Denied
```

See below an image showing intermittent success and failures when attempting to `s3 ls` the bootstrap bucket from a newly joined GovCloud account 
![image](https://user-images.githubusercontent.com/414608/131354262-77086c36-e86a-477c-a708-3e5c96910cda.png)

## Resolution

Adding in a retry mechanism for the step function seems to address this issue reliably.  I have a branch that I will submit soon for review.  Thanks!

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues with the latest release.
