### ISSUE TITLE
Deployment of Serverless Applications does not fully work

### ISSUE THREAD

**Issue by apachler** [awslabs/aws-deployment-framework#388]
As described in the [docs](https://github.com/awslabs/aws-deployment-framework/blob/master/docs/user-guide.md#deploying-serverless-applications-with-sam) it is possible to deploy Serverless Applications through ADF.

I have configured everything as described but got no working results.

The problem here is that the command 'sam build' does not pull dependencies as defined in requirements.txt or package.json for Lambda functions. To fix the problem it is simply needed to update the AWS SAM CLI which is installed in the version 1.15.0 and this version seems not to pull dependencies.

I have upgraded the AWS SAM CLI to 1.31.0 and everything is working like a charm.

**Comment by sbkok** [comment]
Thanks for reporting this.

We are working towards the next release of ADF where the SAM CLI will be updated to a version that fixes your issue.
Your workaround should fix it for the time being. Let me know if you are blocked so we can find another workaround instead.

I will leave this issue open so you will be notified when it is released.
