### ISSUE TITLE
Timeout on Deployment Account's Step Function

### ISSUE THREAD

**Issue by stemons** [awslabs/aws-deployment-framework#400]
Hello team, we have an issue on Deployment Account's Step Function.
Every time the user push some changes to bootstrap repository or just release change, the step function in deployment account reach the 900 seconds timeout.
The environment consists of about 200 accounts and 18 regions.
Step function is trying to iterate over all the accounts and regions to apply the changes to adf-cloudformation-role (adding regional S3 bucket and kms to the policy) even if the policy is correct and no need additional changes.
Any workaround to skip the step function if not needed and proceed with the other bootstrap activities?

**Comment by sbkok** [comment]
Thanks for reporting the issue.
As you might have noticed, @StewartW is working on a fix for this issue.

Once merged, I will leave this issue open until it is released as part of the next version of ADF.

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
Please open a new issue if you are experiencing any issues with the latest release.
