### ISSUE TITLE
Delete default VPC also for regions with "OptInStatus":"opted-in" 

### ISSUE THREAD

**Issue by stefl3n** [awslabs/aws-deployment-framework#420]
Hi,
I read and I also checked on AWS that actually it's not possible to enable the Milan region via API call, so I'm following the manual procedure since ADF can't do that without API.

But about deleting default VPC, is it possible to enable this action for this region when it's enabled?

I'm reading inside ADF code that actually the regions where this happens are the regions with "OptInStatus":'opt-in-not-required'
Is it possible to add also "opted-in" regions?

Let me know!

Thanks,

Stefano

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
Please open a new issue if you are experiencing any issues with the latest release.
