### ISSUE TITLE
Use KMS encryption for ADF notifications

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-deployment-framework#422]
## Why

From a compliance point of view we need all SNS topics to be encrypted. The pipeline notifications topic is currently not using encryption.

## Proposal

As Werner Vogels once said: 

> Dance Like Nobody’s Watching. Encrypt Like Everyone Is

So we should:
- ~Use the AWS managed KMS key by default.~
- ~Make use of a Customer Managed KMS Key optional.~
- Use the default KMS key created by ADF.

## Feedback?

Do you know the year Werner used that quote on stage at re:Invent? I can't remember the year... 

But please contribute in this discussion!

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this feature has been [released as part of v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues related to this feature.
