### ISSUE TITLE
ADF/New pipeline: IndexError: list index out of range

### ISSUE THREAD

**Issue by mirceaadam** [awslabs/aws-deployment-framework#435]
Hi, 

We are getting the below error when trying to create a new pipeline:

```
2022-02-04 11:15:26,985 | INFO | cdk_stacks.main | Pipeline creation/update of infra-cdk-networkroutes commenced | (main.py:31)
Traceback (most recent call last):
  File "adf-build/cdk/generate_pipeline_stacks.py", line 37, in <module>
    main()
  File "adf-build/cdk/generate_pipeline_stacks.py", line 33, in main
    PipelineStack(app, stack_input)
  File "/codebuild/output/src442369410/src/adf-build/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/codebuild/output/src442369410/src/adf-build/cdk/cdk_stacks/main.py", line 195, in __init__
    _is_approval = targets[0].get('name', '').startswith('approval') or \
IndexError: list index out of range
Subprocess exited with error 1
[Container] 2022/02/04 11:15:27 Command did not exit successfully cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null exit status 1
[Container] 2022/02/04 11:15:27 Phase complete: BUILD State: FAILED
[Container] 2022/02/04 11:15:27 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null. Reason: exit status 1
```

We never had this issue before, it is new.
Any ideas how to troubleshoot this ? Thank you

**Comment by Nr18** [comment]
@mirceaadam do you have any targets defined in your pipeline?

My guess is that `_is_approval = targets[0]` is causing the IndexError, so if the targets are empty you cannot fetch the first element `[0]`.

**Comment by mirceaadam** [comment]
Hi @Nr18 ,  We have 18 targets defined

**Comment by Nr18** [comment]
Looking at the source code of `3.1.2` (I assume you use that one)

```python
for index, targets in enumerate(stack_input['input'].get('environments', {}).get('targets', [])):
```

The targets are empty (based on the error message). The `targets` are set by ☝️ that. So if the `environments` are not set or do not include targets you may get this error.

I would suggest have a close look at the pipeline definition. Maybe some hidden characters are in the file? Or the indenting is off. I noticed that this area is totally refactored in the master branch so in 3.2.0 this will be handled completely different.

**Comment by kritro** [comment]
We now reverted back back to a commit in aws-deployment-framework-pipelines from before this happened, an the error still is there, but seems related to another pipeline, so maybe its not related to one specific pipeline at all.

2022-02-07 10:14:47,474 | INFO | cdk_stacks.main | Pipeline creation/update of infra-citrix-infrastructure commenced | (main.py:31)

Traceback (most recent call last):
  File "adf-build/cdk/generate_pipeline_stacks.py", line 37, in <module>
    main()
  File "adf-build/cdk/generate_pipeline_stacks.py", line 33, in main
    PipelineStack(app, stack_input)
  File "/codebuild/output/src770968879/src/adf-build/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/codebuild/output/src770968879/src/adf-build/cdk/cdk_stacks/main.py", line 195, in __init__
    _is_approval = targets[0].get('name', '').startswith('approval') or \
IndexError: list index out of range

Subprocess exited with error 1
[Container] 2022/02/07 10:14:47 Command did not exit successfully cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null exit status 1
[Container] 2022/02/07 10:14:47 Phase complete: BUILD State: FAILED

We use 3.1.2

**Comment by kritro** [comment]
Is it safe to temporarily comment out/remove pipelines from deployment map? If take them back later, would they still be connected to the same cloudformation stacks in the accounts with the resources?

**Comment by Nr18** [comment]
@kritro if you comment them out they will not be removed, they remain as is. When you put them back and the names still resolve to the same name it will re-use the previous CloudFormation stack.

**Comment by kritro** [comment]
Solved in the end. The problem seems to be that we had an AWS account that was suspended, to be deleted, which was in many of the targets. Was not possible to see from the error message, but for sure, when removing those targets, it worked

**Comment by mirceaadam** [comment]
I am closing the issue as we found out the root cause on why the error happened.
Thank you very much for the assistance
