### ISSUE TITLE
python error during build phase

### ISSUE THREAD

**Issue by stemons** [awslabs/aws-deployment-framework#440]
Hello team,

I noticed the following error during the build phase. This error is common to several pipelines.

[Container] 2022/02/18 12:58:32 Running command pip install -r adf-build/requirements.txt -q
--
24 | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lv6q_hbc/MarkupSafe/
25 | You are using pip version 18.1, however version 22.0.3 is available.
26 | You should consider upgrading via the 'pip install --upgrade pip' command.

This has been resolved with a pip upgrade

**Comment by StewartW** [comment]
If you update the requirements.txt file in adf-build (Located in your bootstrap repository) to mirror the current version in master (https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/requirements.txt) 

That appears to resolve this issue.

**Comment by stemons** [comment]
It worked. Thanks!

**Comment by hynynen** [comment]
Same here, had this problem and fixed it.

It would be good to have a bit faster release cycle, or some other mechanism to stay up-to-date with ADF without making full update via SAM.

**Comment by jcfdeb** [comment]
Also has worked for us in a pipeline but still failing in another one.

Using the 'requirements.txt' posted by @StewartW 

```bash
[Container] 2022/02/21 13:30:36 Waiting for agent ping
--
2 | [Container] 2022/02/21 13:30:38 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2022/02/21 13:30:38 Phase is DOWNLOAD_SOURCE
4 | [Container] 2022/02/21 13:30:38 CODEBUILD_SRC_DIR=/codebuild/output/src311577082/src
5 | [Container] 2022/02/21 13:30:38 YAML location is /codebuild/output/src311577082/src/buildspec.yml
6 | [Container] 2022/02/21 13:30:38 No commands found for phase name: install
7 | [Container] 2022/02/21 13:30:38 Processing environment variables
8 | [Container] 2022/02/21 13:30:38 [WARN] Skipping install of runtimes. Runtime version selection is not supported by this build image.
9 | [Container] 2022/02/21 13:30:40 Moving to directory /codebuild/output/src311577082/src
10 | [Container] 2022/02/21 13:30:40 Registering with agent
11 | [Container] 2022/02/21 13:30:40 Phases found in YAML: 3
12 | [Container] 2022/02/21 13:30:40  INSTALL: 0 commands
13 | [Container] 2022/02/21 13:30:40  PRE_BUILD: 2 commands
14 | [Container] 2022/02/21 13:30:40  BUILD: 2 commands
15 | [Container] 2022/02/21 13:30:40 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
16 | [Container] 2022/02/21 13:30:40 Phase context status code:  Message:
17 | [Container] 2022/02/21 13:30:40 Entering phase INSTALL
18 | [Container] 2022/02/21 13:30:40 Phase complete: INSTALL State: SUCCEEDED
19 | [Container] 2022/02/21 13:30:40 Phase context status code:  Message:
20 | [Container] 2022/02/21 13:30:40 Entering phase PRE_BUILD
21 | [Container] 2022/02/21 13:30:40 Running command aws s3 cp s3://$S3_BUCKET_NAME/adf-build/ adf-build/ --recursive --quiet
22 |  
23 | [Container] 2022/02/21 13:30:41 Running command pip install -r adf-build/requirements.txt -q
24 | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-f7dve6km/MarkupSafe/
25 | You are using pip version 18.1, however version 22.0.3 is available.
26 | You should consider upgrading via the 'pip install --upgrade pip' command.
27 |  
28 | [Container] 2022/02/21 13:31:00 Command did not exit successfully pip install -r adf-build/requirements.txt -q exit status 1
29 | [Container] 2022/02/21 13:31:00 Phase complete: PRE_BUILD State: FAILED
30 | [Container] 2022/02/21 13:31:00 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: pip install -r adf-build/requirements.txt -q. Reason: exit status 1
```

It was in the 'build' phase of our 'adf-pipeline-config' pipeline 


Best regards

**Comment by stemons** [comment]
A quick update. I solved the issue on bootstrap pipeline adding the correct version of the libraries in requirements.txt, but we have the same issue on the other pipelines that try to install the requirements:

`

[Container] 2022/02/18 17:06:26 Running command pip install -r adf-build/requirements.txt -q
--
24 | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-v6ndtyow/MarkupSafe/
25 | You are using pip version 18.1, however version 22.0.3 is available.
26 | You should consider upgrading via the 'pip install --upgrade pip' command.
27 |  
28 | [Container] 2022/02/18 17:06:43 Command did not exit successfully pip install -r adf-build/requirements.txt -q exit status 1
29 | [Container] 2022/02/18 17:06:43 Phase complete: PRE_BUILD State: FAILED
30 | [Container] 2022/02/18 17:06:43 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: pip install -r adf-build/requirements.txt -q. Reason: exit status 1

`

**Comment by stemons** [comment]
I solved adding 

`- pip install --upgrade pip` in the buildspec.yml of each pipeline before

`pip install -r adf-build/requirements.txt -q`

**Comment by AndreasAugustin** [comment]
Hi, we solved it with using an other image then the default one:

```yaml
build:
  provider: codebuild
  properties:
    image: STANDARD_5_0
```

the `pip` version is newer then on the standard one.
