### ISSUE TITLE
Idea: allow approval of pipelines without having to go to CodePipeline interface

### ISSUE THREAD

**Issue by ottokruse** [awslabs/aws-deployment-framework#45]
E.g. directly through a command in Slack, or a signed URL in an email.

Would involve writing some Lambda's and such

**Comment by bundyfx** [comment]
Great idea and I think it would be beneficial for users - This would require a fair amount of work but we should start the discussion. 

What would be your proposed solution to this? 

My thought here is we need public interface to receive a hook from slack based on the users approval action which would live on the deployment account along with the associated lambda function to process the event and put the action into effect. This of course would all be optional.

**Comment by bundyfx** [comment]
Closing this one due to inactivity.
