### ISSUE TITLE
bug: Deployment account bootstrap fails, due to Jinja2 dependency issue in Initial Commit Handler

### ISSUE THREAD

**Issue by javydekoning** [awslabs/aws-deployment-framework#454]
The Lambda errors out with this error

```
cannot import name 'soft_unicode' from 'markupsafe' 
```

This seems to be related to: https://github.com/pallets/markupsafe/issues/286

Pinning `markupsafe` will resolve it. 

I suggest pinning `markupsafe==2.0.1` + bumping the Jinja2 version to `3.1.1` to fix the issue.

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
Please open a new issue if you are experiencing any issues with the latest release.
