### ISSUE TITLE
bug: AccountManagementStateMachine can't invoke AccountAliasConfigurationFunction

### ISSUE THREAD

**Issue by javydekoning** [awslabs/aws-deployment-framework#460]
Error:

```json
{
  "error": "Lambda.AWSLambdaException",
  "cause": "User: arn:aws:sts::xxxx:assumed-role/serverlessrepo-aws-deploy-StateMachineExecutionRol-YYXZKF1DNVEG/GGzJDbzYyvarbIioekwoULLKpGuSfJRc is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:xxxx:function:AccountAliasConfigurationFunction because no identity-based policy allows the lambda:InvokeFunction action (Service: AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Request ID: c0c4199a-20fa-472e-a106-471bfdaa742e; Proxy: null)"
}
```

Reason:

https://github.com/awslabs/aws-deployment-framework/blob/adeaf11a00b3473fad0b79104bc3cf76cf2b0139/src/account_processing.yml#L144-L151

The role instead of the function is referenced. Use `!GetAtt AccountAliasConfigFunction.Arn` instead to fix.

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
Please open a new issue if you are experiencing any issues with the latest release.
