### ISSUE TITLE
feat: set codecommit repository description

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-deployment-framework#468]
We want to set the CodeCommit description from the deployment map. And looking at the ADF codebase it is partially implemented already. So I figured that I would complete the feature ;-) since we want to make use of it.

The implementation is really simple, see: #469

But I noticed that the `codecommit:UpdateRepository` action is part of the IAM permissions for the `adf-automation-role`. But this permission does not exist at all. You have `codecommit:UpdateRepositoryName` and `codecommit:UpdateRepositoryDescription`.

Changing a repository name is tricky, so that should not be there (I think) but the `codecommit:UpdateRepository` action should be changed to `codecommit:UpdateRepositoryDescription` IMHO.

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this feature has been [released as part of v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues related to this feature.
