### ISSUE TITLE
Idea: adding ADF version as CFN output parameter and CodeBuild log

### ISSUE THREAD

**Issue by deltagarrett** [awslabs/aws-deployment-framework#47]
This will be useful in order to check which ADF version is running during the ADF update process

**Comment by bundyfx** [comment]
Thanks @deltagarrett 

Would this just be a hardcoded version number in all ADF resources containing the version number as an output and is bumped on every Release made?

**Comment by deltagarrett** [comment]
Exactly, something very simple to propagate (and maintain) but that can provide you immediate feedback on which ADF version you are running.
