### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded for role adf-codepipeline-role

### ISSUE THREAD

**Issue by stefl3n** [awslabs/aws-deployment-framework#474]
Hi,
we're experiencing issues with the aws-deployment-framework-bootstrap since the StateMachine "EnableCrossAccountAccess" in the deployment account is failing.

Here some details about the error we're getting:
![1527_485_1](https://user-images.githubusercontent.com/48389722/173075124-f9a120ad-d557-4c61-b615-a73d2599161a.png)

It seems the error is about the adf-codepipeline-role policy since is exceeding the limit.

Looking in the deployment account I found new empty buckets created today and they are the same we can find in the policy.

I think these new buckets are added in the policy resources and it exceeds the limit probably!

![1501_548_1](https://user-images.githubusercontent.com/48389722/173076315-136b456f-0340-4127-9f6b-49fc5e3cb881.png)

I hope it's clear!

Thanks,

Stefano

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
Please open a new issue if you are experiencing any issues with the latest release.
