### ISSUE TITLE
bug: resourcegroupstaggingapi does not return organizations resources

### ISSUE THREAD

**Issue by christianherweg0807** [awslabs/aws-deployment-framework#476]
I tried to use this with my AWS organization, but just get an empty result.

https://github.com/awslabs/aws-deployment-framework/blob/9a32492209d35660b9ece66211eb200b64dc0ef9/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py#L264-L277

After that I tried to reproduce manually. with the "ResourceTypeFilters=['organizations']", assumed an Payer-Admin-Role like this:
```
import boto3
tag_client=boto3.client(
             'resourcegroupstaggingapi',
             region_name='eu-central-1',
         )
paging=tag_client.get_paginator('get_resources')

for resource in paging.paginate(ExcludeCompliantResources=False, ResourceTypeFilters=['organizations']):
  print(resource)
 ```

Result:
```
{'PaginationToken': '', 'ResourceTagMappingList': [], 'ResponseMetadata': {'RequestId': 'a4dd9273-99f7-4c24-b117-14c791a4959c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'a4dd9273-99f7-4c24-b117-14c791a4959c', 'content-type': 'application/x-amz-json-1.1', 'content-length': '50', 'date': 'Wed, 06 Jul 2022 07:01:34 GMT'}, 'RetryAttempts': 0}}
```

I don´t understand, why it's empty... we have many accounts in the organizations service with & without tags at account level.

Am I missing something?

thank you
Christian

**Comment by thomasklinger1234** [comment]
The issue seems to be that the region needs to be `us-east-1` for organizations resources to work. For later reference :)

**Comment by christianherweg0807** [comment]
That did the clue. Thank you Thomas
