### ISSUE TITLE
Error in bootstrap

### ISSUE THREAD

**Issue by CakeHockey** [awslabs/aws-deployment-framework#546]
Hi,
I was trying to modify my AWS Organization setup (changing OUs, moving accounts into OU, ecc...) and the deployment process failed with this error:

Traceback (most recent call last):
--
129 | File "adf-build/main.py", line 348, in <module>
130 | main()
131 | File "adf-build/main.py", line 326, in main
132 | thread.join()
133 | File "/codebuild/output/src243054070/src/adf-build/shared/python/thread.py", line 30, in join
134 | raise self.exc
135 | File "/codebuild/output/src243054070/src/adf-build/shared/python/thread.py", line 20, in run
136 | self.ret = self._target(
137 | File "adf-build/main.py", line 203, in worker_thread
138 | parameter_store.put_parameter(
139 | File "/codebuild/output/src243054070/src/adf-build/shared/python/parameter_store.py", line 31, in put_parameter
140 | current_value = self.fetch_parameter(name)
141 | File "/codebuild/output/src243054070/src/adf-build/shared/python/parameter_store.py", line 76, in fetch_parameter
142 | response = self.client.get_parameter(
143 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
144 | return self._make_api_call(operation_name, kwargs)
145 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
146 | raise error_class(parsed_response, operation_name)
147 | botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetParameter operation: The security token included in the request is invalid
148 |  
149 | [Container] 2022/10/10 13:38:59 Command did not exit successfully python adf-build/main.py exit status 1
150 | [Container] 2022/10/10 13:38:59 Phase complete: BUILD State: FAILED
151 | [Container] 2022/10/10 13:38:59 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: python adf-build/main.py. Reason: exit status 1
152 | [Container] 2022/10/10 13:38:59 Entering phase POST_BUILD
153 | [Container] 2022/10/10 13:38:59 Phase complete: POST_BUILD State: SUCCEEDED
154 | [Container] 2022/10/10 13:38:59 Phase context status code:  Message:

How can I solve it? It seems like there is an error in the deployment account

**Comment by 20FS21** [comment]
Hello all,
I have exactly the same problem in my ADF configuration.
ADF support team do you have some idea to fix this issue?
thanks a lot.

**Comment by sbkok** [comment]
Thanks for reporting this issue.
How long did the bootstrap CodeBuild machine run before it threw this error?

Did you adopt any new accounts recently? And lastly, what regions are you interacting with (Deployment region / target regions)?

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!
