### ISSUE TITLE
Suggest to loosen the dependency on schema

### ISSUE THREAD

**Issue by Agnes-U** [awslabs/aws-deployment-framework#552]
Hi, your project aws-deployment-framework(commit id: 0723ddf4eaf55888ae780dc48873f0ec4766cfbd) requires "schema==0.7.5" in its dependency. After analyzing the source code, we found that the following versions of schema can also be suitable, i.e., schema 0.7.4, since all functions that you directly (7 APIs: schema.Schema.__init__, schema.And.__init__, schema.Optional.__init__, schema.Use.__init__, schema.Regex.__init__, schema.Or.__init__, schema.SchemaError.__init__) or indirectly (propagate to 1 schema's internal APIs and 1 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on schema from "schema==0.7.5" to "schema>=0.7.4,<=0.7.5". This will improve the applicability of aws-deployment-framework and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on schema?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by sbkok** [comment]
Since the [schema library](https://github.com/keleshev/schema) never published version 0.7.4, or they pulled it from their releases I suggest we don't broaden the scope.
There must be a reason why they pulled it in the first place.
Hence closing this request.
