### ISSUE TITLE
replace Jinja2 with CDK

### ISSUE THREAD

**Issue by bundyfx** [awslabs/aws-deployment-framework#56]
Jinja2 can become complex to manage as templates grow and contain more logic. It would be easier to have CDK applications for each pipeline type that work in the same way Jinja2 does now.

**Comment by triha74** [comment]
I was actually just about to bring this up that cdk support should be added.

So yes please. +1

**Comment by bundyfx** [comment]
Moving this to 1.2.0 release as CDK is not yet out of developer preview.

**Comment by bundyfx** [comment]
moved to 1.3.0 which will be the next major focus point 🎉
