### ISSUE TITLE
ADF new version release

### ISSUE THREAD

**Issue by dbrasilaws** [awslabs/aws-deployment-framework#591]
Hi team, I hope your are doing well and safe.

Is there any ETA when the new ADF version will be released?

Regards,
Diego Brasil

**Comment by sbkok** [comment]
Hi @dbrasilaws,

The plan is to release it this week.
Unless a blocking issue is found of course.
We tested ADF at various organizations so far, and the latest release candidate did not show any blocking issues.

Best regards, Simon

**Comment by sbkok** [comment]
I am happy to inform you that we [released v3.2.0](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.0) just now.
I'm hereby closing this issue.
