### ISSUE TITLE
[Bug]: AccountManagementStateMachine does not start when creating new account.

### ISSUE THREAD

**Issue by PasiPP** [awslabs/aws-deployment-framework#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We updated ADF to 3.2.0 recently and discovered that `AccountManagementStateMachine` and `AccountBootstrappingStateMachine` does not start while creating a new account under `aws-deployment-framework-bootstrap/adf-accounts`. The bootstrap pipeline goes through nicely and flows to deployment account, where other actions are performed accordingly.

State machines (`AccountManagementStateMachine, AccountBootstrappingStateMachine`) in management account are present and active, but they never run. Therefore we can't currently create an account via ADF.

### Expected Behavior

We expect that the bootstrap pipeline triggers the state machines which handles the account creation process on management account.

### Current Behavior

The LogLevel on `serverlessrepo-aws-deployment-framework` was set on DEBUG but it gave no clear reason why the state machine does not start. Everything runs trough successfully pipeline wise and therefore we don't have a clear sight on the possible fix. 

For now, there is nothing that seems to trigger the state machines in the management account.

### ADF Version

3.2.0

**Comment by StewartW** [comment]
Hi, 

Just to confirm, do you have a cloudtrail configured for your management account?

**Comment by PasiPP** [comment]
We encountered the following error during the troubleshoot: 

`| 1675090318187 | [ERROR] InvalidName: An error occurred (InvalidName) when calling the StartExecution operation: Invalid Name: 'Example - Test Account Prod-3deb1ba1-03f9-400a-a37c-4dd8c2bd6147-a4b87fe1f04d' Traceback (most recent call last):   File "/var/task/process_account_files.py", line 200, in lambda_handler     start_executions(   File "/var/task/process_account_files.py", line 174, in start_executions     sfn_client.start_execution(   File "/var/task/botocore/client.py", line 530, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/task/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore     return xray_recorder.record_subsegment(   File "/var/task/aws_xray_sdk/core/recorder.py", line 462, in record_subsegment     six.raise_from(exc, exc)   File "<string>", line 3, in raise_from   File "/var/task/aws_xray_sdk/core/recorder.py", line 457, in record_subsegment     return_value = wrapped(*args, **kwargs)   File "/var/task/botocore/client.py", line 960, in _make_api_call     raise error_class(parsed_response, operation_name). `

It seems that when adding a new account to the `new-accounts-adf.yml` file with white space in the account_full_name (`Example - Test Account Prod`), the `AccountFileProcessorFunction` Lambda which calls the Step Functions gives the error message, because of the Step Function execution name must not contain white space.

The Lambda gets the execution name from the `new-accounts-adf.yml` and due to limitations related to State Machine Executions, the account creation process is failing.

This is tested in another environment successfully. When naming the new account as `Example-Test_Account_Prod` the account creation process goes through smoothly.

We are currently creating a workaround on this, but this is definitely something to be looked at so there wouldn't be a need for changing naming conventions for new and existing accounts.

**Comment by niklaswesterstrahleknowit** [comment]
From what I picked up from Pasi and his colleague..

This should be fixed:
`)
    for account in processed_account_list:
        full_account_name = account.get('account_full_name', 'no-account-name')
        # AWS Step Functions supports max 80 characters.
        # Since the run_id equals 49 characters plus the dash, we have 30
        # characters available. To ensure we don't run over, lets use a
        # truncated version instead:
        truncated_account_name = full_account_name[:30]
        sfn_execution_name = f"{truncated_account_name}-{run_id}"`

with something like this

`       # Account name can contain characters that execution name do not allow
        # Scrub name from illegal chars
        
        forbidden_chars = [ " ", "<", ">", "{", "}", "[", "]", "?", "*", "#", "%", "\", "^"", "|", "~", "$", "&", ",", ";", ":", "/"]
                               
        for character in forbidden_chars:
            truncated_account_name = truncated_account_name.replace(character, "")
            
        sfn_execution_name = f"{truncated_account_name}-{run_id}"`

Just my five cents copy pasting the data :)
