### ISSUE TITLE
ADF VPC Pipeline in AWS fails during build phase

### ISSUE THREAD

**Issue by Marta-Danelli** [awslabs/aws-deployment-framework#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi!

I've created an AWS account through adf-pipeline.
The account was created successfully but when I run the adf-pipeline-vpc to add the CIDR for the VPC the build phase fails with the logs pasted below.
Did someone encounter a similar error and what's the solution?

[Container] 2023/02/09 13:32:22 Running command python adf-build/generate_params.py
[Container] 2023/02/09 13:32:27 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2023/02/09 13:32:27 Phase context status code: Message:

[Container] 2023/02/09 13:32:27 Entering phase BUILD
[Container] 2023/02/09 13:32:27 Running command bash adf-build/helpers/package_transform.sh
Perform build step

SAM CLI now collects telemetry to better understand customer needs.
You can OPT OUT and disable telemetry collection by setting the
environment variable SAM_CLI_TELEMETRY=0 in your shell.
Thanks for your help!

Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

Building codeuri: ./src runtime: python3.7 metadata: {} functions: ['AuthorizationLambda']
Running PythonPipBuilder:ResolveDependencies

Build Failed

Error: PythonPipBuilder:ResolveDependencies - {charset-normalizer==3.0.1(wheel)}

[Container] 2023/02/09 13:32:32 Command did not exit successfully bash adf-build/helpers/package_transform.sh exit status 1
[Container] 2023/02/09 13:32:32 Phase complete: BUILD State: FAILED
[Container] 2023/02/09 13:32:32 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: bash adf-build/helpers/package_transform.sh. Reason: exit status 1

[Container] 2023/02/09 13:32:33 Entering phase POST_BUILD
[Container] 2023/02/09 13:32:33 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2023/02/09 13:32:33 Phase context status code: Message:
[Container] 2023/02/09 13:32:33 Expanding base directory path: .
[Container] 2023/02/09 13:32:33 Assembling file list
[Container] 2023/02/09 13:32:33 Expanding .
[Container] 2023/02/09 13:32:33 Expanding file paths for base directory .
[Container] 2023/02/09 13:32:33 Assembling file list
[Container] 2023/02/09 13:32:33 Expanding */
[Container] 2023/02/09 13:32:33 Found 2005 file(s)
[Container] 2023/02/09 13:32:34 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
[Container] 2023/02/09 13:32:34 Phase context status code: Message:

### Expected Behavior

the build succeeds and the VPC is created

### Current Behavior

[logs pipeline.txt](https://github.com/awslabs/aws-deployment-framework/files/10699876/logs.pipeline.txt)

### ADF Version

3.1.2

**Comment by deltagarrett** [comment]
Hi @Marta-Danelli can you share ADF version (3.1.2?) and the `buildspec.yml` you are using?

**Comment by Marta-Danelli** [comment]
Hi @deltagarrett the version I'm using is the  3.1.2

Here's the buildspec:
[buildspec.txt](https://github.com/awslabs/aws-deployment-framework/files/10705162/buildspec.txt)

**Comment by StewartW** [comment]
It looks like a problem with your AuthorizationLambda. When executing the transform on it, it fails to install dependencies. Have you checked the pinned versions of your dependencies / requirements for the authorization lambda.

**Comment by sbkok** [comment]
I'm closing this issue as it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in the meanwhile.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/awslabs/aws-deployment-framework/releases).

Thank you!
