### ISSUE TITLE
There is already a Construct with name 'iam-target-1-wave-0' in Stack [iam]

### ISSUE THREAD

**Issue by andrebrc** [awslabs/aws-deployment-framework#627]
We are using deployment maps to create pipelines and when I try to include a new target in some existent pipelines, I've got the error below after the state machine runs the codebuild project:

2023-04-25 12:12:39,443 \| INFO \| __main__ \| ADF Version 3.2.0 \| (generate_pipeline_stacks.py:27)
179 | 2023-04-25 12:12:39,444 \| INFO \| __main__ \| ADF Log Level is INFO \| (generate_pipeline_stacks.py:28)
180 | 2023-04-25 12:12:39,453 \| INFO \| cdk_stacks.main \| Pipeline creation/update of iam commenced \| (main.py:36)
181 | jsii.errors.JavaScriptError:
182 | Error: There is already a Construct with name 'iam-target-1-wave-0' in Stack [iam]
183 | at Node.addChild (/tmp/jsii-kernel-Nkb8Pe/node_modules/constructs/lib/construct.js:458:19)
184 | at new Node (/tmp/jsii-kernel-Nkb8Pe/node_modules/constructs/lib/construct.js:35:28)
185 | at new ConstructNode (/tmp/jsii-kernel-Nkb8Pe/node_modules/@aws-cdk/core/lib/construct-compat.js:174:28)
186 | at Object.createNode (/tmp/jsii-kernel-Nkb8Pe/node_modules/@aws-cdk/core/lib/construct-compat.js:35:42)
187 | at new Construct (/tmp/jsii-kernel-Nkb8Pe/node_modules/constructs/lib/construct.js:503:32)
188 | at new Construct (/tmp/jsii-kernel-Nkb8Pe/node_modules/@aws-cdk/core/lib/construct-compat.js:33:9)
189 | at Kernel._create (/tmp/tmpx_9xgv50/lib/program.js:9964:29)
190 | at Kernel.create (/tmp/tmpx_9xgv50/lib/program.js:9693:29)
191 | at KernelHost.processRequest (/tmp/tmpx_9xgv50/lib/program.js:11544:36)
192 | at KernelHost.run (/tmp/tmpx_9xgv50/lib/program.js:11504:22)

I was thinking of deleting the stacks and re-execute the aws-deployment-framework-pipelines.

Any idea how to solve it?

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.1](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.1) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues with the latest release.
