### ISSUE TITLE
[Feat]: Re-enable cfn-lint

### ISSUE THREAD

**Issue by javydekoning** [awslabs/aws-deployment-framework#629]
### Describe the feature

Re-enable `cfn-lint` in megalinter config when [megalinter](https://github.com/oxsecurity/megalinter) has release a new build with the latest cfn-lint.

### Use Case

Re-enable `cfn-lint` in megalinter config when [megalinter](https://github.com/oxsecurity/megalinter) has release a new build with the latest cfn-lint.

### Acknowledgements

- [X] I may be able to implement this feature request

**Comment by nvuillam** [comment]
Will happen with v7 that will be released in the next week :)

If you are in a hurry, you can already use [beta](https://github.com/oxsecurity/megalinter/issues/2608) version, that embeds cfn-lint v0.77.5 :) (compared to 0.76.1 in latest MegaLinter 6.22.2)

Another workaround with current version could be to upgrade cfn-lint in a [pre-command](https://megalinter.io/latest/configuration/#pre-commands) before it is called

```yaml
PRE_COMMANDS:
  - command: pip3 install --no-cache-dir cfn-lint=='0.77.5'
    venv: cfn-lint
```

**Comment by javydekoning** [comment]
Thanks @nvuillam , appreciate your response here. We'll move to v7 when it's out :-)! For now we are OK as cfn-lint runs in another flow as well.
