### ISSUE TITLE
Remove ssm params when removing base stacks

### ISSUE THREAD

**Issue by thomasmcgannon** [awslabs/aws-deployment-framework#63]
Currently when the remove_base option is set, moving an account to the root OU will remove the base stack, however to completely clean an account from ADF resources we need to manually go into the account and remove some SSM params.

Can the logic which removes the base stacks be extended to remove these SSM params as well? This could perhaps be done by adding Tags to the params which can be filtered on.

This would significantly simplify the process to re-bootstrap accounts and move them between OUs

**Comment by bundyfx** [comment]
Agreed, this is a nice addition to cleaning up the "base" stack/resources when moving account back to root with the remove-base configuration enabled.
