### ISSUE TITLE
[Bug]: DeleteDefaultVPC fails with OptInRequired

### ISSUE THREAD

**Issue by markymarkus** [awslabs/aws-deployment-framework#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Osaka(ap-northeast-3) DeleteDefaultVPC fails in new account creation. This error only happens occasionally. I tried to reproduce it in our test - AWS Organizations but there DeleteDefaultVPC finished without any errors. 

### Expected Behavior

All default VPCs should be deleted after the account creation finishes.

### Current Behavior

AccountManagementStateMachine stops in 'Failed' status.

DeleteDefaultVPC Lambda has failed.
**Input**:
{
  "Payload": {
    "account_id": ".....",
    "region": "ap-northeast-3"
  }
}

**Output**:
{
  "errorMessage": "An error occurred (OptInRequired) when calling the DescribeVpcs operation: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.",
  "errorType": "ClientError",
  "requestId": "485795bc-f736-422f-aeac-2ccd7df0f3d6",
  "stackTrace": [
    "  File \"/var/task/delete_default_vpc.py\", line 72, in lambda_handler\n    default_vpc_id = find_default_vpc(ec2_client)\n",
    "  File \"/var/task/delete_default_vpc.py\", line 28, in find_default_vpc\n    vpc_response = ec2_client.describe_vpcs()\n",
    "  File \"/var/task/botocore/client.py\", line 530, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/task/aws_xray_sdk/ext/botocore/patch.py\", line 38, in _xray_traced_botocore\n    return xray_recorder.record_subsegment(\n",
    "  File \"/var/task/aws_xray_sdk/core/recorder.py\", line 462, in record_subsegment\n    six.raise_from(exc, exc)\n",
    "  File \"<string>\", line 3, in raise_from\n",
    "  File \"/var/task/aws_xray_sdk/core/recorder.py\", line 457, in record_subsegment\n    return_value = wrapped(*args, **kwargs)\n",
    "  File \"/var/task/botocore/client.py\", line 960, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}

### ADF Version

3.2.0

**Comment by niklaswesterstrahleknowit** [comment]
We ran into this same issue in ap-south-1 in one of our environments. So +1 to this.

**Comment by javydekoning** [comment]
@sbkok this may sometimes happen on new accounts, it's a race condition. Could you add some retry logic here?

Something along these lines (untested):

```python
import retrying
from botocore.exceptions import ClientError
import time

@retrying.retry(
    stop_max_attempt_number=5,
    wait_exponential_multiplier=10000,  # 10 seconds
    wait_exponential_max=60000  # Maximum backoff time of 60 seconds
)
def find_default_vpc(ec2_client):
    try:
        vpc_response = ec2_client.describe_vpcs()
        for vpc in vpc_response["Vpcs"]:
            if vpc.get("IsDefault", False):
                return vpc["VpcId"]
    except ClientError as e:
        # Log the error if needed
        print("An error occurred:", e)
        # Raise the exception to trigger the retry logic
        raise
    # If no default VPC found, return None
    return None
```
