### ISSUE TITLE
[Feat]: New release

### ISSUE THREAD

**Issue by alFReD-NSH** [awslabs/aws-deployment-framework#658]
### Describe the feature

With all the new changes, it would be nice to have a new release.

### Use Case

Get the new changes.

### Acknowledgements

- [ ] I may be able to implement this feature request

**Comment by donnyDonowitz** [comment]
please create a new release!! need CDK v2

**Comment by javydekoning** [comment]
We're working on it. We have a few more changes coming before v4.0.0.
