### ISSUE TITLE
Detailed samples for Service Catalog / ETL pipelines

### ISSUE THREAD

**Issue by bundyfx** [awslabs/aws-deployment-framework#68]
The samples folder should contain a detailed sample for many different types of pipelines such as Service Catalog Product deployment, ETL, Serverless Applications.

**Comment by jordan-evans** [comment]
Would be especially interested in the Service Catalog examples. I wasn't aware ADF supported Service Catalog until I saw this.

**Comment by bundyfx** [comment]
> Would be especially interested in the Service Catalog examples. I wasn't aware ADF supported Service Catalog until I saw this.

Yep, ADF is aimed at supporting deployments of anything! - I've got some detailed samples of some Service Catalog, ETL and Serverless Apps coming in the next minor release *(next few days)*
