### ISSUE TITLE
[Chore]: Upgrade GitHub CodeQL Action v2 to v3

### ISSUE THREAD

**Issue by sbkok** [awslabs/aws-deployment-framework#698]
## Why?

As can be seen at the following [GitHub MegaLinter Job](https://github.com/awslabs/aws-deployment-framework/actions/runs/8461369655/job/23181032522?pr=697): when it attempts to upload the MegaLinter scan results to the GitHub Security tab, it states that CodeQL Action v2 will be deprecated on December 5th, 2024.

## What?

It seems we need to upgrade to v3: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

**Comment by javydekoning** [comment]
Completed in #704
