### ISSUE TITLE
ADF new version release

### ISSUE THREAD

**Issue by itsnotsagar** [awslabs/aws-deployment-framework#723]
Hi team, I hope your are doing well and safe.

Is there any ETA when the new ADF version will be released?

**Comment by sbkok** [comment]
Hi @itsnotsagar,

Thank you for your inquiry about the upcoming release of the new ADF version. We appreciate your patience and understanding as our development team is working diligently to ensure the highest quality for this release.

Currently, we are in the final testing phase, and if no major issues arise, we are confident that the v4.0 release will be available within the next few weeks. Rest assured that our team is committed to delivering this update as soon as possible while maintaining the highest standards of quality and reliability.

We understand the importance of this release for our users, and we are eager to share the new features and improvements with you. Please stay tuned for further updates, and thank you once again for your continued support.

Best regards, Simon

**Comment by itsnotsagar** [comment]
Thanks @sbkok for the update.
Can you confirm if issue #724 will be part of this update?

**Comment by sbkok** [comment]
Thank you for your patience. I am pleased to inform you that [v4.0.0 is released](https://github.com/awslabs/aws-deployment-framework/releases/tag/v4.0.0) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues related to this release.
