### ISSUE TITLE
[Bug]: Account creation is broken since the release of lambda runtime 3.9v51

### ISSUE THREAD

**Issue by igordust** [awslabs/aws-deployment-framework#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm observing today that the usual account creation procedure is broken. I observed it in three different ADF installations so I'm pretty sure that the impact is quite wide. Looking at the last successful execution, I notice that the lambda runtime has been updated, it was 3.9v46, now it's 3.9v51.

### Expected Behavior

AccountFileProcess should run without errors and account creation should be performed

### Current Behavior

Once submitted a new account configuration file, after the bootstrap pipeline has completed successfully, AccountFileProcessorFunction throws this exception:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'process_account_files': cannot import name 'DEPRECATED_SERVICE_NAMES' from 'botocore.docs' (/var/task/botocore/docs/__init__.py)
Traceback (most recent call last):
``` 

### Steps To Reproduce

1. create a new account configuration file in adf-accounts in the bootstrap repository
2. commit it
3. wait for bootstrap pipeline to complete
4. go to AccountFileProcessorFunction lambda function and check the error

### Possible Solution

The error is caused by a pretty old botocore version (1.29.54) packaged with the lambda, that is incompatible with the boto3 version now available in the runtime, that is 1.34.42.
The botocore version is not in the requirements, is a dependency of aws-xray-sdk, so the botocore version you find depends on the moment you installed ADF.

My suggestion is to fix both boto3 and botocore version explicitly in the requirements.
I would also suggest to check everywhere else there might such a similar issue.

### ADF Version

3.2.0

### Contributing a fix?

- [ ] Yes, I am working on a fix to resolve this issue

**Comment by sbkok** [comment]
Thank you for your patience. I am happy to inform you that this issue has been [resolved in our latest release v3.2.1](https://github.com/awslabs/aws-deployment-framework/releases/tag/v3.2.1) just now.
I'm hereby closing this issue. Please open a new issue if you are experiencing any issues with the latest release.
