### ISSUE TITLE
Parallel generation of pipelines

### ISSUE THREAD

**Issue by triha74** [awslabs/aws-deployment-framework#77]
When processing the deployment map sequentially adding pipelines makes it slower and slower to get a new pipe generated. Parallelising the process would be appreciated in order to increase creation speed.

**Comment by bundyfx** [comment]
Does this relate to #79 also? We can also treat each pipeline in a similar fashion as we do to base stacks in the bootstrap pipeline in which we create a thread for each pipeline.. along with the map split change of course. In that case, we can create a thread for each map and then a thread for each pipeline in each map.
