### ISSUE TITLE
Split deployment map into sub files

### ISSUE THREAD

**Issue by triha74** [awslabs/aws-deployment-framework#78]
One single file for the deployment map has several issues. 

1. Single point of failure. All teams and developers push to the same yml config file. This is fragile as a single malformed entry in the yml can break the pipeline creation for all teams and introduces cross team blocker situations.

2. Hard to automate adding new repositories and pipelines. Ultimately I would like to see a single click creation of git repo and pipeline. If each app could have its own deployment_map file then this would be much easier to script.

**Comment by bundyfx** [comment]
Resolved by #79 
Thank you!
