### ISSUE TITLE
Consider renaming example configs

### ISSUE THREAD

**Issue by mikael-lindstrom** [awslabs/aws-deployment-framework#8]
Currently [adfconfig.yml](https://github.com/awslabs/aws-deployment-framework/blob/master/src/bootstrap_repository/adfconfig.yml) and [deployment_map.yml](https://github.com/awslabs/aws-deployment-framework/blob/master/src/pipelines_repository/deployment_map.yml) contain examples and will be changed for each deployment. It would be easier to keep in sync with this repo and avoid merge conflicts if the files where named differently, e.g. `adfconfig-example.yml`.

**Comment by bundyfx** [comment]
Thanks Mikael, we will include an update to the naming of the files in the next minor release to make keeping in-sync with master easier.
