### ISSUE TITLE
pyyml 5 conflicts with aws-sam-cli

### ISSUE THREAD

**Issue by oaksenov** [awslabs/aws-deployment-framework#81]
in python requirements file src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/requirements.txt aws-sam-cli conflicts with pyyaml~=5.1.
Maybe it is going to ok to use PyYAML-3.13 instead ?

**Comment by bundyfx** [comment]
Pyyaml 5.1 is the latest stable version, Until other packages that depend on an older version update this non terminating error will be displayed. As part of implementing yaml 1.2 specs we will be updating to ruamel in the next few minor releases - this relates to #75 and will be solved at the same time
