### ISSUE TITLE
Document the "Delete Scenario"

### ISSUE THREAD

**Issue by triha74** [awslabs/aws-deployment-framework#84]
When installing the new SAR deployed version of ADF I tried to uninstall my current version and its not easy to find all the stacks that need to be delete in all the accounts and regions.

Also once that was done I saw that there where still config parameters left in Parameter Store from the old install. These I guess are not created by Cloudformation so they become orphans. I would actually prefer that all ADF config parameters had a path starting with /adf.

So a good documentation and full implementation of a unistall would be nice.

Tomas

**Comment by bundyfx** [comment]
Working on this now along with a bunch of other updates to the docs!
