### ISSUE TITLE
Upgrading between version should not make changes to global.yml

### ISSUE THREAD

**Issue by bundyfx** [awslabs/aws-deployment-framework#85]
When making the PR with the new content for ADF we should ignore global.yml in the root of the repository.

**Comment by thiezn** [comment]
Hi @bundyfx,

We've not only been updating the global.yml in the root folder of the bootstrap repository. We've also made changes to the deployment/global.yml and deployment/regional.yml to allow our codebuild stage to do things in the master account for the Organizational and FMS api's. 

Perhaps all the global.yml's can be renamed to global-example.yml to avoid overwriting any customer customization.

Cheers,
Thiezn
