### ISSUE TITLE
Rename base stacks to follow global-base naming structure

### ISSUE THREAD

**Issue by bundyfx** [awslabs/aws-deployment-framework#92]
Currently when bootstrapping an AWS Account it will receive the base global stack (and optional regional stacks). This stack is named based on the OU the account was moved into, not the level in which the account applied its specific base template. A larger change here would push for the idea that the base stacks are all named the same, this allows for accounts to be moved from OU to OU and allows for base stacks to update as opposed having to move them back to the root to remove and back into some other OU for a new base stack. We should investigate how to best make this more transparent and streamlined.

**Comment by triha74** [comment]
Just keep backward compatibility in mind please
